<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_PccWMKvUEfGGjYEUN-iB-A" name="RescueSync" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_PdZ_gKvUEfGGjYEUN-iB-A" name="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_PflJwKvUEfGGjYEUN-iB-A" name="Municipio" actor="_6KsysKvaEfGGjYEUN-iB-A">
        <elements xmi:type="process:StartEvent" xmi:id="_Pfx-EKvUEfGGjYEUN-iB-A" name="Inicio" outgoing="_Pjtb0KvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PfylIavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PfylIKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PfylIqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PgCcwKvUEfGGjYEUN-iB-A" name="Cargar emergencia" outgoing="_Pj1-sKvUEfGGjYEUN-iB-A" incoming="_Pjtb0KvUEfGGjYEUN-iB-A" actor="_6KsysKvaEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PgDD0avUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PgDD0KvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PgDD0qvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PgDD06vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PgDD1KvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PgDD1avUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PgDD16vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PgDD1qvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PgDD2avUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PgDD2qvUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PgDD2KvUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PgDD26vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PgS7cKvUEfGGjYEUN-iB-A" name="Seleccionar ofertas" outgoing="_PlEGsKvUEfGGjYEUN-iB-A" incoming="_PlAcUKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PgTigavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PgTigKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PgTigqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PgTig6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PgTihKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PgTihavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PgTih6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PgTihqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PgTiiavUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PgTiiqvUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PgTiiKvUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PgTii6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PgZCEKvUEfGGjYEUN-iB-A" name="Centro coordinador regional" actor="_FfUhkKvbEfGGjYEUN-iB-A">
        <elements xmi:type="process:Task" xmi:id="_Pghk8KvUEfGGjYEUN-iB-A" name="Revisar emergencia" outgoing="_Pj7eQKvUEfGGjYEUN-iB-A" incoming="_Pj1-sKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pghk8qvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pghk8avUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pghk86vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pghk9KvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pghk9avUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pghk9qvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pghk-KvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pghk96vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PgiMAKvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PgiMAavUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Pghk-avUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PgiMAqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PgoSoKvUEfGGjYEUN-iB-A" name="Generar lotes de necesidades" outgoing="_PkBk4KvUEfGGjYEUN-iB-A" incoming="_Pj7eQKvUEfGGjYEUN-iB-A _Pks6UKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pgo5savUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pgo5sKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pgo5sqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pgo5s6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pgo5tKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pgo5tavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pgo5t6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pgo5tqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Pgo5uavUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_Pgo5uqvUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Pgo5uKvUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Pgo5u6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PgvAUKvUEfGGjYEUN-iB-A" name="Publicar convocatoria" outgoing="_Pmm-0KvUEfGGjYEUN-iB-A" incoming="_PkBk4KvUEfGGjYEUN-iB-A _PknawKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PgvAUqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PgvAUavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PgvAU6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PgvAVKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PgvAVavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PgvAVqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PgvAWKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PgvAV6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PgvnYavUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PgvnYqvUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PgvnYKvUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PgvnY6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Pg2VEKvUEfGGjYEUN-iB-A" name="Evaluar cobertura" outgoing="_PkhUIKvUEfGGjYEUN-iB-A" incoming="_Pn7NcKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pg2VEqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pg2VEavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pg2VE6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pg2VFKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pg2VFavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pg2VFqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pg2VGKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pg2VF6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Pg2VGqvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_Pg2VG6vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Pg2VGavUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Pg2VHKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Pg8bsKvUEfGGjYEUN-iB-A" name="¿Qué acción tomar?" outgoing="_PknawKvUEfGGjYEUN-iB-A _Pks6UKvUEfGGjYEUN-iB-A _Pk0PEKvUEfGGjYEUN-iB-A" incoming="_PkhUIKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pg9CwavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pg9CwKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pg9CwqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PhMTUKvUEfGGjYEUN-iB-A" name="Sistema">
        <elements xmi:type="process:ServiceTask" xmi:id="_PhdZEKvUEfGGjYEUN-iB-A" name="Enviar ofertas a Sistema Nacional" outgoing="_PkVG4KvUEfGGjYEUN-iB-A" incoming="_Ed-8MKviEfGPjbJOghg_xg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PhdZEqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PhdZEavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PhdZE6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PhdZFKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PhdZFavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PhdZFqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PhdZGKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PhdZF6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PhgcYKvUEfGGjYEUN-iB-A" name="Asignar ofertas" outgoing="_PlAcUKvUEfGGjYEUN-iB-A" incoming="_Pk0PEKvUEfGGjYEUN-iB-A _PnzRoKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PhgcYqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PhgcYavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PhhDcKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PhhDcavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PhhDcqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PhhDc6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PhhDdavUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PhhDdKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Phkt0KvUEfGGjYEUN-iB-A" name="Registrar adjudicación" outgoing="_Pm8WAKvUEfGGjYEUN-iB-A" incoming="_PlEGsKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Phkt0qvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Phkt0avUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Phkt06vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Phkt1KvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Phkt1avUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Phkt1qvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Phkt2KvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Phkt16vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PhoYMKvUEfGGjYEUN-iB-A" name="Enviar compromiso" outgoing="_PlNQoKvUEfGGjYEUN-iB-A" incoming="_PnER0KvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pho_QavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pho_QKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pho_QqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pho_Q6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pho_RKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pho_RavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pho_R6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pho_RqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PhxiIKvUEfGGjYEUN-iB-A" name="Informar finalización" outgoing="_Mq450K1vEfGhg4iXH2Bxcg" incoming="_5h1iQKviEfGPjbJOghg_xg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PhyJMavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PhyJMKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PhyJMqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PhyJM6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PhyJNKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PhyJNavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PhyJN6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PhyJNqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Ph1zkKvUEfGGjYEUN-iB-A" name="Enviar Notificacion Formal" outgoing="_PnTiYKvUEfGGjYEUN-iB-A" incoming="_PnK_gKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ph1zkqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ph1zkavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ph1zk6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ph1zlKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ph1zlavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ph1zlqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ph1zmKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ph1zl6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Ph76MKvUEfGGjYEUN-iB-A" name="Notificar SN y a ONG" outgoing="_PnER0KvUEfGGjYEUN-iB-A _PnK_gKvUEfGGjYEUN-iB-A" incoming="_Pm8WAKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ph76MqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ph76MavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ph76M6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_PiBZwKvUEfGGjYEUN-iB-A" name="¿Alcanzan las cantidades?" outgoing="_PnzRoKvUEfGGjYEUN-iB-A _Pn7NcKvUEfGGjYEUN-iB-A" incoming="_6MQ7sKxYEfG6DcibwtxsHw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiBZwqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiBZwavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiBZw6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_EtxyoKxZEfG6DcibwtxsHw" name="Evaluar cantidades habilitadas" outgoing="_6MQ7sKxYEfG6DcibwtxsHw" incoming="_PlI_MKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GkbnsaxYEfG6DcibwtxsHw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GkbnsKxYEfG6DcibwtxsHw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GkbnsqxYEfG6DcibwtxsHw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Gkbns6xYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GkbntKxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GkbntaxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GkcOwKxYEfG6DcibwtxsHw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GkbntqxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PhFloKvUEfGGjYEUN-iB-A" name="Notificar ONGs" outgoing="_Pmu6oKvUEfGGjYEUN-iB-A" incoming="_Pmm-0KvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PhFloqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PhFloavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PhFlo6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PhGMsKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PhGMsavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PhGMsqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PhGMtKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PhGMs6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Pf6tkK1sEfGhg4iXH2Bxcg" name="Monitoreo de actividades" outgoing="_PlrKsKvUEfGGjYEUN-iB-A" incoming="_RFPFkK1sEfGhg4iXH2Bxcg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pf8iwK1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pf77sK1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pf8iwa1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pf8iwq1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pf8iw61sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pf8ixK1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pf8ixq1sEfGhg4iXH2Bxcg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pf8ixa1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_vSrCoK1uEfGhg4iXH2Bxcg" name="¿Terminaron todas las ONG sus actividades?" outgoing="_PmMvIKvUEfGGjYEUN-iB-A _WnOnIK1vEfGhg4iXH2Bxcg" incoming="_Mq450K1vEfGhg4iXH2Bxcg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vSrpsa1uEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vSrpsK1uEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vSrpsq1uEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PiGSQKvUEfGGjYEUN-iB-A" name="ONG" actor="_SeZAEKvbEfGGjYEUN-iB-A">
        <elements xmi:type="process:Task" xmi:id="_PiMY4KvUEfGGjYEUN-iB-A" name="Desplegar recursos" outgoing="_PnZpAKvUEfGGjYEUN-iB-A" incoming="_PlZd4KvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiMY4qvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiMY4avUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiMY46vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PiMY5KvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PiMY5avUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PiMY5qvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PiMY6KvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PiMY56vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PiMY6qvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PiMY66vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PiMY6avUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PiMY7KvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PiQqUKvUEfGGjYEUN-iB-A" name="Marcar actividades como finalizadas" outgoing="_RFPFkK1sEfGhg4iXH2Bxcg" incoming="_PnZpAKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiQqUqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiQqUavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiQqU6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PiQqVKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PiQqVavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PiQqVqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PiQqWKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PiQqV6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PiQqWqvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PiQqW6vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PiQqWavUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PiQqXKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PiU7wKvUEfGGjYEUN-iB-A" name="Cargar oferta de ayuda" incoming="_Pmu6oKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiU7wqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiU7wavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiU7w6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_HAMzkKvdEfGGjYEUN-iB-A" name="tiempoTerminado" dataType="_PcgAkKvUEfGGjYEUN-iB-A">
            <defaultValue xmi:type="expression:Expression" xmi:id="_HAMzkavdEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean"/>
          </data>
          <data xmi:type="process:JavaObjectData" xmi:id="_a6szIKvdEfGGjYEUN-iB-A" name="tiempoEspera" dataType="_PcgnpavUEfGGjYEUN-iB-A" className="java.time.Duration">
            <defaultValue xmi:type="expression:Expression" xmi:id="_a6szIavdEfGGjYEUN-iB-A" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.Duration"/>
          </data>
          <data xmi:type="process:Data" xmi:id="_i92xQKvdEfGGjYEUN-iB-A" name="ventanaDeCarga" dataType="_PcgnoqvUEfGGjYEUN-iB-A">
            <defaultValue xmi:type="expression:Expression" xmi:id="_i92xQavdEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PiU7xKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PiU7xavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PiU7xqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PiU7yKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PiU7x6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_PjKCMKvUEfGGjYEUN-iB-A" name="Ventana de ofertas" outgoing="_Ed-8MKviEfGPjbJOghg_xg">
            <condition xmi:type="expression:Expression" xmi:id="_yph1YKvcEfGGjYEUN-iB-A" name="ventanaDeCarga" content="ventanaDeCarga" type="TYPE_VARIABLE" returnType="java.lang.Long">
              <referencedElements xmi:type="process:Data" xmi:id="_je8sIKvdEfGGjYEUN-iB-A" name="ventanaDeCarga" dataType="_PcgnoqvUEfGGjYEUN-iB-A"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PiU7yqvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PiU7y6vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PiU7yavUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PiU7zKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PibpcKvUEfGGjYEUN-iB-A" name="Ejecutar actividades" outgoing="_PlZd4KvUEfGGjYEUN-iB-A" incoming="_PnTiYKvUEfGGjYEUN-iB-A _7GImkKviEfGPjbJOghg_xg _WnOnIK1vEfGhg4iXH2Bxcg" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PibpcqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PibpcavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pibpc6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PibpdKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PibpdavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PibpdqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PibpeKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pibpd6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PibpeqvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_Pibpe6vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PibpeavUEfGGjYEUN-iB-A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PibpfKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_txZaEKviEfGPjbJOghg_xg" name="¿Quedan actividades?" outgoing="_5h1iQKviEfGPjbJOghg_xg _7GImkKviEfGPjbJOghg_xg" incoming="_PlrKsKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pif64qvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pif64avUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pif646vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PikzYKvUEfGGjYEUN-iB-A" name="Sistema nacional">
        <elements xmi:type="process:ServiceTask" xmi:id="_PirhEKvUEfGGjYEUN-iB-A" name="Evaluar habilitación/competencia" outgoing="_PlI_MKvUEfGGjYEUN-iB-A" incoming="_PkVG4KvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PirhEqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PirhEavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PirhE6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PirhFKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PirhFavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PirhFqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PirhGKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PirhF6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PivygKvUEfGGjYEUN-iB-A" name="Registrar compromiso de recursos" outgoing="_PlTXQKvUEfGGjYEUN-iB-A" incoming="_PlNQoKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PivygqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PivygavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pivyg6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PivyhKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PivyhavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PivyhqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PivyiKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pivyh6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Pizc4KvUEfGGjYEUN-iB-A" name="Bloquear recursos" outgoing="_BAOJ0K1sEfGhg4iXH2Bxcg" incoming="_PlTXQKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pizc4qvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pizc4avUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pizc46vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pizc5KvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pizc5avUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pizc5qvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pizc6KvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pizc56vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Pi3HQKvUEfGGjYEUN-iB-A" name="Marcar proyecto como terminado" outgoing="_PmXuQKvUEfGGjYEUN-iB-A" incoming="_PmMvIKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pi3HQqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pi3HQavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pi3HQ6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pi3HRKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pi3HRavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pi3HRqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pi3HSKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pi3HR6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Pi6xoKvUEfGGjYEUN-iB-A" name="Liberar recursos" outgoing="_PmfDAKvUEfGGjYEUN-iB-A" incoming="_PmXuQKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pi6xoqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pi6xoavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pi6xo6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pi6xpKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pi6xpavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pi6xpqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pi6xqKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pi6xp6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_PjA4QKvUEfGGjYEUN-iB-A" name="Fin" incoming="_PmfDAKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PjBfUavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PjBfUKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PjBfUqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_A_oT8K1sEfGhg4iXH2Bxcg" name="Fin" incoming="_BAOJ0K1sEfGhg4iXH2Bxcg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A_-5Qa1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A_-5QK1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A_-5Qq1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_PfhfYKvUEfGGjYEUN-iB-A" name="quedanActividades" dataType="_PcgAkKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_PfhfYavUEfGGjYEUN-iB-A" name="" content="" returnType=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_poERYKvbEfGGjYEUN-iB-A" name="coberturaMinima" dataType="_PcgAkKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_poERYavbEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_OnB3gKvcEfGGjYEUN-iB-A" name="opcionElegida" dataType="_PcgnpKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_OnB3gavcEfGGjYEUN-iB-A" name="" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_re3lgKvcEfGGjYEUN-iB-A" name="estaHabilitado" dataType="_PcgAkKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_re3lgavcEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_e4JUcK1vEfGhg4iXH2Bxcg" name="cantTerminadas" dataType="_PcgnoavUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_e4JUca1vEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Integer"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Pe-FwKvUEfGGjYEUN-iB-A">
        <targetForm xmi:type="expression:Expression" xmi:id="_Pe-FwavUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Pe-FwqvUEfGGjYEUN-iB-A">
        <targetForm xmi:type="expression:Expression" xmi:id="_Pe-Fw6vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pjtb0KvUEfGGjYEUN-iB-A" target="_PgCcwKvUEfGGjYEUN-iB-A" source="_Pfx-EKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pjtb0avUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pjtb0qvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pj1-sKvUEfGGjYEUN-iB-A" target="_Pghk8KvUEfGGjYEUN-iB-A" source="_PgCcwKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pj1-savUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pj1-sqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pj7eQKvUEfGGjYEUN-iB-A" target="_PgoSoKvUEfGGjYEUN-iB-A" source="_Pghk8KvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pj7eQavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pj7eQqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PkBk4KvUEfGGjYEUN-iB-A" target="_PgvAUKvUEfGGjYEUN-iB-A" source="_PgoSoKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PkBk4avUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PkBk4qvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PkVG4KvUEfGGjYEUN-iB-A" target="_PirhEKvUEfGGjYEUN-iB-A" source="_PhdZEKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PkVG4avUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PkVG4qvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PkhUIKvUEfGGjYEUN-iB-A" target="_Pg8bsKvUEfGGjYEUN-iB-A" source="_Pg2VEKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PkhUIavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PkhUIqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PknawKvUEfGGjYEUN-iB-A" name="Reabrir convocatoria" target="_PgvAUKvUEfGGjYEUN-iB-A" source="_Pg8bsKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PknawavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PknawqvUEfGGjYEUN-iB-A" name="opcionElegida" content="opcionElegida" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pks6UKvUEfGGjYEUN-iB-A" name="Reformular lotes" target="_PgoSoKvUEfGGjYEUN-iB-A" source="_Pg8bsKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pks6UavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pks6UqvUEfGGjYEUN-iB-A" name="opcionElegida" content="opcionElegida" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pk0PEKvUEfGGjYEUN-iB-A" name="Enviar ofertas igualmente" target="_PhgcYKvUEfGGjYEUN-iB-A" source="_Pg8bsKvUEfGGjYEUN-iB-A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pk0PEavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pk0PEqvUEfGGjYEUN-iB-A" name="opcionElegida" content="opcionElegida" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlAcUKvUEfGGjYEUN-iB-A" target="_PgS7cKvUEfGGjYEUN-iB-A" source="_PhgcYKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlAcUavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PlAcUqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlEGsKvUEfGGjYEUN-iB-A" target="_Phkt0KvUEfGGjYEUN-iB-A" source="_PgS7cKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlEGsavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PlEGsqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlI_MKvUEfGGjYEUN-iB-A" target="_EtxyoKxZEfG6DcibwtxsHw" source="_PirhEKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlI_MavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PlI_MqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlNQoKvUEfGGjYEUN-iB-A" target="_PivygKvUEfGGjYEUN-iB-A" source="_PhoYMKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlNQoavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PlNQoqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlTXQKvUEfGGjYEUN-iB-A" target="_Pizc4KvUEfGGjYEUN-iB-A" source="_PivygKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlTXQavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PlTXQqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlZd4KvUEfGGjYEUN-iB-A" target="_PiMY4KvUEfGGjYEUN-iB-A" source="_PibpcKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlZd4avUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PlZd4qvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PlrKsKvUEfGGjYEUN-iB-A" target="_txZaEKviEfGPjbJOghg_xg" source="_Pf6tkK1sEfGhg4iXH2Bxcg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PlrKsavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tkIaIqviEfGPjbJOghg_xg" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PmMvIKvUEfGGjYEUN-iB-A" name="Sí" target="_Pi3HQKvUEfGGjYEUN-iB-A" source="_vSrCoK1uEfGhg4iXH2Bxcg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PmMvIavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PmMvIqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PmXuQKvUEfGGjYEUN-iB-A" target="_Pi6xoKvUEfGGjYEUN-iB-A" source="_Pi3HQKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PmXuQavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PmXuQqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PmfDAKvUEfGGjYEUN-iB-A" target="_PjA4QKvUEfGGjYEUN-iB-A" source="_Pi6xoKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PmfqEKvUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PmfqEavUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pmm-0KvUEfGGjYEUN-iB-A" target="_PhFloKvUEfGGjYEUN-iB-A" source="_PgvAUKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pmm-0avUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pmm-0qvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pmu6oKvUEfGGjYEUN-iB-A" target="_PiU7wKvUEfGGjYEUN-iB-A" source="_PhFloKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pmu6oavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pmu6oqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pm8WAKvUEfGGjYEUN-iB-A" target="_Ph76MKvUEfGGjYEUN-iB-A" source="_Phkt0KvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pm8WAavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pm8WAqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PnER0KvUEfGGjYEUN-iB-A" target="_PhoYMKvUEfGGjYEUN-iB-A" source="_Ph76MKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PnER0avUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PnER0qvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PnK_gKvUEfGGjYEUN-iB-A" target="_Ph1zkKvUEfGGjYEUN-iB-A" source="_Ph76MKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PnK_gavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PnK_gqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PnTiYKvUEfGGjYEUN-iB-A" target="_PibpcKvUEfGGjYEUN-iB-A" source="_Ph1zkKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PnTiYavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PnTiYqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PnZpAKvUEfGGjYEUN-iB-A" target="_PiQqUKvUEfGGjYEUN-iB-A" source="_PiMY4KvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PnaQEKvUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PnaQEavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PnzRoKvUEfGGjYEUN-iB-A" name="Sí" target="_PhgcYKvUEfGGjYEUN-iB-A" source="_PiBZwKvUEfGGjYEUN-iB-A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PnzRoavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PnzRoqvUEfGGjYEUN-iB-A" name="estaHabilitado" content="estaHabilitado" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_rfROIKvcEfGGjYEUN-iB-A" name="estaHabilitado" dataType="_PcgAkKvUEfGGjYEUN-iB-A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pn7NcKvUEfGGjYEUN-iB-A" name="No" target="_Pg2VEKvUEfGGjYEUN-iB-A" source="_PiBZwKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pn7NcavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pn7NcqvUEfGGjYEUN-iB-A" name="estaHabilitado" content="estaHabilitado" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_soMlEKvcEfGGjYEUN-iB-A" name="estaHabilitado" dataType="_PcgAkKvUEfGGjYEUN-iB-A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ed-8MKviEfGPjbJOghg_xg" target="_PhdZEKvUEfGGjYEUN-iB-A" source="_PjKCMKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EeBYcKviEfGPjbJOghg_xg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EeBYcaviEfGPjbJOghg_xg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5h1iQKviEfGPjbJOghg_xg" name="No" target="_PhxiIKvUEfGGjYEUN-iB-A" source="_txZaEKviEfGPjbJOghg_xg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5h2JUKviEfGPjbJOghg_xg"/>
        <condition xmi:type="expression:Expression" xmi:id="_5h2JUaviEfGPjbJOghg_xg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7GImkKviEfGPjbJOghg_xg" name="Si" target="_PibpcKvUEfGGjYEUN-iB-A" source="_txZaEKviEfGPjbJOghg_xg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7GImkaviEfGPjbJOghg_xg"/>
        <condition xmi:type="expression:Expression" xmi:id="_7GImkqviEfGPjbJOghg_xg" name="quedanActividades" content="quedanActividades" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_a1cbgKvkEfGPjbJOghg_xg" name="quedanActividades" dataType="_PcgAkKvUEfGGjYEUN-iB-A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6MQ7sKxYEfG6DcibwtxsHw" target="_PiBZwKvUEfGGjYEUN-iB-A" source="_EtxyoKxZEfG6DcibwtxsHw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6MQ7saxYEfG6DcibwtxsHw"/>
        <condition xmi:type="expression:Expression" xmi:id="_6MQ7sqxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BAOJ0K1sEfGhg4iXH2Bxcg" target="_A_oT8K1sEfGhg4iXH2Bxcg" source="_Pizc4KvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BAPX8K1sEfGhg4iXH2Bxcg"/>
        <condition xmi:type="expression:Expression" xmi:id="_BAP_AK1sEfGhg4iXH2Bxcg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RFPFkK1sEfGhg4iXH2Bxcg" target="_Pf6tkK1sEfGhg4iXH2Bxcg" source="_PiQqUKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RFPsoK1sEfGhg4iXH2Bxcg"/>
        <condition xmi:type="expression:Expression" xmi:id="_RFPsoa1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Mq450K1vEfGhg4iXH2Bxcg" target="_vSrCoK1uEfGhg4iXH2Bxcg" source="_PhxiIKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Mq5g4K1vEfGhg4iXH2Bxcg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Mq5g4a1vEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WnOnIK1vEfGhg4iXH2Bxcg" name="No" target="_PibpcKvUEfGGjYEUN-iB-A" source="_vSrCoK1uEfGhg4iXH2Bxcg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WnOnIa1vEfGhg4iXH2Bxcg"/>
        <condition xmi:type="expression:Expression" xmi:id="_WnOnIq1vEfGhg4iXH2Bxcg" name="cantTerminadas > 0" content="cantTerminadas > 0" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_6KsysKvaEfGGjYEUN-iB-A" name="Empleado municipal" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_FfUhkKvbEfGGjYEUN-iB-A" name="Empleado centro coordinador"/>
      <actors xmi:type="process:Actor" xmi:id="_SeZAEKvbEfGGjYEUN-iB-A" name="Responsable ONG"/>
      <contract xmi:type="process:Contract" xmi:id="_Pe-s0KvUEfGGjYEUN-iB-A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7pgKvUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7pgavUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7pgqvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7pg6vUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7phKvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7phavUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7phqvUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7ph6vUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7piKvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7piavUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7piqvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7pi6vUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7pjKvUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7pjavUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7pjqvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_PcgAkKvUEfGGjYEUN-iB-A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_PcgnoKvUEfGGjYEUN-iB-A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_PcgnoavUEfGGjYEUN-iB-A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_PcgnoqvUEfGGjYEUN-iB-A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Pcgno6vUEfGGjYEUN-iB-A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_PcgnpKvUEfGGjYEUN-iB-A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_PcgnpavUEfGGjYEUN-iB-A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_PchOsKvUEfGGjYEUN-iB-A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_PchOsavUEfGGjYEUN-iB-A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_PceLYKvUEfGGjYEUN-iB-A" type="Process" element="_PccWMKvUEfGGjYEUN-iB-A" name="RescueSync - habilitación- 1.0 - 1.0 (1)" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_PfDlUKvUEfGGjYEUN-iB-A" type="2007" element="_PdZ_gKvUEfGGjYEUN-iB-A">
      <children xmi:type="notation:DecorationNode" xmi:id="_PfEMZKvUEfGGjYEUN-iB-A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_PfEMZavUEfGGjYEUN-iB-A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_PfmX4KvUEfGGjYEUN-iB-A" type="3007" element="_PflJwKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PfmX5avUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PfmX5qvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PfzzQKvUEfGGjYEUN-iB-A" type="3002" element="_Pfx-EKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pf0aUKvUEfGGjYEUN-iB-A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Pf0aUavUEfGGjYEUN-iB-A" x="-28" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PfzzQavUEfGGjYEUN-iB-A" x="180" y="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PgFgEKvUEfGGjYEUN-iB-A" type="3005" element="_PgCcwKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PgGuMKvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgFgEavUEfGGjYEUN-iB-A" x="280" y="61" width="145" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PgUJkKvUEfGGjYEUN-iB-A" type="3005" element="_PgS7cKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PgUJkqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgUJkavUEfGGjYEUN-iB-A" x="1685" y="57" width="158" height="79"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PfmX4avUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PfmX4qvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PfmX46vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PfmX56vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PfmX5KvUEfGGjYEUN-iB-A" x="53" y="10" width="3952" height="203"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PgZpIKvUEfGGjYEUN-iB-A" type="3007" element="_PgZCEKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PgZpJavUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PgZpJqvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PgizEKvUEfGGjYEUN-iB-A" type="3005" element="_Pghk8KvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PgizEqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgizEavUEfGGjYEUN-iB-A" x="280" y="115" width="158" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PgpgwKvUEfGGjYEUN-iB-A" type="3005" element="_PgoSoKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PgpgwqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgpgwavUEfGGjYEUN-iB-A" x="466" y="115" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pgw1gKvUEfGGjYEUN-iB-A" type="3005" element="_PgvAUKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pgw1gqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pgw1gavUEfGGjYEUN-iB-A" x="675" y="115" width="139" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pg28IKvUEfGGjYEUN-iB-A" type="3005" element="_Pg2VEKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pg28IqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pg28IavUEfGGjYEUN-iB-A" x="884" y="169" width="124" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pg9p0KvUEfGGjYEUN-iB-A" type="3008" element="_Pg8bsKvUEfGGjYEUN-iB-A" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pg9p0qvUEfGGjYEUN-iB-A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Pg9p06vUEfGGjYEUN-iB-A" y="-65"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pg9p0avUEfGGjYEUN-iB-A" x="924" y="52"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PgZpIavUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PgZpIqvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PgZpI6vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PgZpJ6vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgZpJKvUEfGGjYEUN-iB-A" x="3982" y="80" height="304"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PhMTUavUEfGGjYEUN-iB-A" type="3007" element="_PhMTUKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PhM6YKvUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PhM6YavUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PhdZGavUEfGGjYEUN-iB-A" type="3027" element="_PhdZEKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PheAIKvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhdZGqvUEfGGjYEUN-iB-A" x="1301" y="131" width="147" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PhhDdqvUEfGGjYEUN-iB-A" type="3027" element="_PhgcYKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhhDeKvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhhDd6vUEfGGjYEUN-iB-A" x="1585" y="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PhlU4KvUEfGGjYEUN-iB-A" type="3027" element="_Phkt0KvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhlU4qvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhlU4avUEfGGjYEUN-iB-A" x="1808" y="52" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pho_SKvUEfGGjYEUN-iB-A" type="3027" element="_PhoYMKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhpmUavUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhpmUKvUEfGGjYEUN-iB-A" x="2018" y="172" width="124" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PhyJOKvUEfGGjYEUN-iB-A" type="3027" element="_PhxiIKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhyJOqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhyJOavUEfGGjYEUN-iB-A" x="3108" y="63" width="142" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ph2aoKvUEfGGjYEUN-iB-A" type="3027" element="_Ph1zkKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ph2aoqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ph2aoavUEfGGjYEUN-iB-A" x="2208" y="60" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ph8hQKvUEfGGjYEUN-iB-A" type="3009" element="_Ph76MKvUEfGGjYEUN-iB-A" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ph9IUKvUEfGGjYEUN-iB-A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ph9IUavUEfGGjYEUN-iB-A" x="8" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ph8hQavUEfGGjYEUN-iB-A" x="2037" y="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PiCA0KvUEfGGjYEUN-iB-A" type="3008" element="_PiBZwKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiCA0qvUEfGGjYEUN-iB-A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PiCA06vUEfGGjYEUN-iB-A" x="114" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiCA0avUEfGGjYEUN-iB-A" x="1543" y="173"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EtxyqaxZEfG6DcibwtxsHw" type="3027" element="_EtxyoKxZEfG6DcibwtxsHw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Etxyq6xZEfG6DcibwtxsHw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EtxyqqxZEfG6DcibwtxsHw" x="1488" y="280" width="154" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PhGzwKvUEfGGjYEUN-iB-A" type="3027" element="_PhFloKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhHa0KvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhGzwavUEfGGjYEUN-iB-A" x="694" y="267"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pf-_AK1sEfGhg4iXH2Bxcg" type="3027" element="_Pf6tkK1sEfGhg4iXH2Bxcg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pf_mEK1sEfGhg4iXH2Bxcg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pf-_Aa1sEfGhg4iXH2Bxcg" x="2777" y="251" width="142" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vSs30K1uEfGhg4iXH2Bxcg" type="3008" element="_vSrCoK1uEfGhg4iXH2Bxcg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_vSte4K1uEfGhg4iXH2Bxcg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vSte4a1uEfGhg4iXH2Bxcg" x="153" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vSs30a1uEfGhg4iXH2Bxcg" x="3177" y="204"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PhMTUqvUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PhMTU6vUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PhMTVKvUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PhM6YqvUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhMTVavUEfGGjYEUN-iB-A" x="48" y="507" width="3957" height="433"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PiG5UKvUEfGGjYEUN-iB-A" type="3007" element="_PiGSQKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PiG5VavUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PiG5VqvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PiM_8KvUEfGGjYEUN-iB-A" type="3005" element="_PiMY4KvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiM_8qvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiM_8avUEfGGjYEUN-iB-A" x="2607" y="57" width="116" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PiQqXavUEfGGjYEUN-iB-A" type="3005" element="_PiQqUKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiRRYKvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiQqXqvUEfGGjYEUN-iB-A" x="2778" y="52" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PiWJ4KvUEfGGjYEUN-iB-A" type="3005" element="_PiU7wKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiWJ4qvUEfGGjYEUN-iB-A" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_PjLQUKvUEfGGjYEUN-iB-A" type="3043" element="_PjKCMKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_PjLQUqvUEfGGjYEUN-iB-A" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_PjLQU6vUEfGGjYEUN-iB-A" x="-25" y="10"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PjLQUavUEfGGjYEUN-iB-A"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiWJ4avUEfGGjYEUN-iB-A" x="783" y="57" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PicQgKvUEfGGjYEUN-iB-A" type="3005" element="_PibpcKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PicQgqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PicQgavUEfGGjYEUN-iB-A" x="2418" y="54" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_txaBI6viEfGPjbJOghg_xg" type="3008" element="_txZaEKviEfGPjbJOghg_xg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_txaBJaviEfGPjbJOghg_xg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_txaBJqviEfGPjbJOghg_xg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_txaBJKviEfGPjbJOghg_xg" x="3015" y="118" width="42" height="42"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PiG5UavUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PiG5UqvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PiG5U6vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PiG5V6vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiG5VKvUEfGGjYEUN-iB-A" x="48" y="940" width="3957" height="285"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PilacKvUEfGGjYEUN-iB-A" type="3007" element="_PikzYKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PiladavUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PiladqvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PisvMKvUEfGGjYEUN-iB-A" type="3027" element="_PirhEKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PisvMqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PisvMavUEfGGjYEUN-iB-A" x="1301" y="107" width="145" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PiwZkKvUEfGGjYEUN-iB-A" type="3027" element="_PivygKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiwZkqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiwZkavUEfGGjYEUN-iB-A" x="2199" y="68" width="144" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pizc6avUEfGGjYEUN-iB-A" type="3027" element="_Pizc4KvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pi0D8KvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pizc6qvUEfGGjYEUN-iB-A" x="2455" y="73" width="129" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pi3HSavUEfGGjYEUN-iB-A" type="3027" element="_Pi3HQKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pi3uUKvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pi3HSqvUEfGGjYEUN-iB-A" x="3095" y="109" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pi7YsKvUEfGGjYEUN-iB-A" type="3027" element="_Pi6xoKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pi7YsqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pi7YsavUEfGGjYEUN-iB-A" x="3419" y="115"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PjCGYKvUEfGGjYEUN-iB-A" type="3003" element="_PjA4QKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PjCGYqvUEfGGjYEUN-iB-A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PjCGY6vUEfGGjYEUN-iB-A" y="9"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PjCGYavUEfGGjYEUN-iB-A" x="3666" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BAG1EK1sEfGhg4iXH2Bxcg" type="3003" element="_A_oT8K1sEfGhg4iXH2Bxcg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_BAIDMK1sEfGhg4iXH2Bxcg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BAIDMa1sEfGhg4iXH2Bxcg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BAG1Ea1sEfGhg4iXH2Bxcg" x="2702" y="100"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PilacavUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PilacqvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Pilac6vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Pilad6vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiladKvUEfGGjYEUN-iB-A" x="53" y="1175" width="3952" height="281"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_PfEMYKvUEfGGjYEUN-iB-A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_PfEMYavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_PfEMYqvUEfGGjYEUN-iB-A" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_PfEMZqvUEfGGjYEUN-iB-A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PfEMY6vUEfGGjYEUN-iB-A" width="3980" height="1447"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_PceLYavUEfGGjYEUN-iB-A"/>
    <edges xmi:type="notation:Connector" xmi:id="_Pjup8KvUEfGGjYEUN-iB-A" type="4001" element="_Pjtb0KvUEfGGjYEUN-iB-A" source="_PfzzQKvUEfGGjYEUN-iB-A" target="_PgFgEKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PjvRAKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PjvRAavUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pjup8avUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pjup8qvUEfGGjYEUN-iB-A" points="[0, 0, -73, 0]$[73, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pj2lwKvUEfGGjYEUN-iB-A" type="4001" element="_Pj1-sKvUEfGGjYEUN-iB-A" source="_PgFgEKvUEfGGjYEUN-iB-A" target="_PgizEKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pj2lw6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pj2lxKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pj2lwavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pj2lwqvUEfGGjYEUN-iB-A" points="[0, 0, 0, -165]$[0, 165, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pj8FUKvUEfGGjYEUN-iB-A" type="4001" element="_Pj7eQKvUEfGGjYEUN-iB-A" source="_PgizEKvUEfGGjYEUN-iB-A" target="_PgpgwKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pj8FU6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pj8FVKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pj8FUavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pj8FUqvUEfGGjYEUN-iB-A" points="[0, 0, -86, 0]$[86, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PkBk46vUEfGGjYEUN-iB-A" type="4001" element="_PkBk4KvUEfGGjYEUN-iB-A" source="_PgpgwKvUEfGGjYEUN-iB-A" target="_Pgw1gKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PkCL8qvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PkCL86vUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PkCL8KvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PkCL8avUEfGGjYEUN-iB-A" points="[0, 0, -109, 0]$[109, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PkVt8KvUEfGGjYEUN-iB-A" type="4001" element="_PkVG4KvUEfGGjYEUN-iB-A" source="_PhdZGavUEfGGjYEUN-iB-A" target="_PisvMKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PkVt86vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PkVt9KvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PkVt8avUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PkVt8qvUEfGGjYEUN-iB-A" points="[0, 0, 0, -615]$[0, 615, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pkh7MKvUEfGGjYEUN-iB-A" type="4001" element="_PkhUIKvUEfGGjYEUN-iB-A" source="_Pg28IKvUEfGGjYEUN-iB-A" target="_Pg9p0KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pkh7M6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pkh7NKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pkh7MavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pkh7MqvUEfGGjYEUN-iB-A" points="[0, 0, 0, 63]$[0, -63, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PkoB0KvUEfGGjYEUN-iB-A" type="4001" element="_PknawKvUEfGGjYEUN-iB-A" source="_Pg9p0KvUEfGGjYEUN-iB-A" target="_Pgw1gKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PkoB06vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PkoB1KvUEfGGjYEUN-iB-A" x="-13" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PkoB0avUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PkoB0qvUEfGGjYEUN-iB-A" points="[0, 0, 191, -12]$[-191, 0, 0, -12]$[-191, 12, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PkthYKvUEfGGjYEUN-iB-A" type="4001" element="_Pks6UKvUEfGGjYEUN-iB-A" source="_Pg9p0KvUEfGGjYEUN-iB-A" target="_PgpgwKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PkthY6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PkthZKvUEfGGjYEUN-iB-A" x="74" y="18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PkthYavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PkthYqvUEfGGjYEUN-iB-A" points="[0, -21, 409, -98]$[-409, -21, 0, -98]$[-409, 42, 0, -35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pk02IKvUEfGGjYEUN-iB-A" type="4001" element="_Pk0PEKvUEfGGjYEUN-iB-A" source="_Pg9p0KvUEfGGjYEUN-iB-A" target="_PhhDdqvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pk02I6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pk02JKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pk02IavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pk02IqvUEfGGjYEUN-iB-A" points="[0, -21, -672, -323]$[275, -21, -397, -323]$[275, -40, -397, -342]$[669, -40, -3, -342]$[669, 292, -3, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qQXDgK1nEfGhg4iXH2Bxcg" id="(0.9302325581395349,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_R5CWoKvjEfGPjbJOghg_xg" id="(0.32,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlAcU6vUEfGGjYEUN-iB-A" type="4001" element="_PlAcUKvUEfGGjYEUN-iB-A" source="_PhhDdqvUEfGGjYEUN-iB-A" target="_PgUJkKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlBDYKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlBDYavUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlAcVKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlAcVavUEfGGjYEUN-iB-A" points="[0, 0, 0, 418]$[0, -418, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_o7XwwKxaEfG6DcibwtxsHw" id="(0.2468354430379747,0.9746835443037974)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlEGs6vUEfGGjYEUN-iB-A" type="4001" element="_PlEGsKvUEfGGjYEUN-iB-A" source="_PgUJkKvUEfGGjYEUN-iB-A" target="_PhlU4KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlFU0KvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlFU0avUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlEGtKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlEGtavUEfGGjYEUN-iB-A" points="[0, 0, 0, -576]$[0, 576, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlJmQKvUEfGGjYEUN-iB-A" type="4001" element="_PlI_MKvUEfGGjYEUN-iB-A" source="_PisvMKvUEfGGjYEUN-iB-A" target="_EtxyqaxZEfG6DcibwtxsHw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlJmQ6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlJmRKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlJmQavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlJmQqvUEfGGjYEUN-iB-A" points="[7, 30, -133, 264]$[175, 30, 35, 264]$[175, -248, 35, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WvgvMKxYEfG6DcibwtxsHw" id="(0.9517241379310345,0.2222222222222222)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ds9EQKxYEfG6DcibwtxsHw" id="(0.49032258064516127,0.974025974025974)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlN3sKvUEfGGjYEUN-iB-A" type="4001" element="_PlNQoKvUEfGGjYEUN-iB-A" source="_Pho_SKvUEfGGjYEUN-iB-A" target="_PiwZkKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlN3s6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlN3tKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlN3savUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlN3sqvUEfGGjYEUN-iB-A" points="[7, 31, -184, -779]$[7, 817, -184, 7]$[119, 817, -72, 7]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlTXQ6vUEfGGjYEUN-iB-A" type="4001" element="_PlTXQKvUEfGGjYEUN-iB-A" source="_PiwZkKvUEfGGjYEUN-iB-A" target="_Pizc6avUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlTXRqvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlTXR6vUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlTXRKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlTXRavUEfGGjYEUN-iB-A" points="[0, 0, -156, 0]$[156, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlZd46vUEfGGjYEUN-iB-A" type="4001" element="_PlZd4KvUEfGGjYEUN-iB-A" source="_PicQgKvUEfGGjYEUN-iB-A" target="_PiM_8KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlZd5qvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlZd56vUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlZd5KvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlZd5avUEfGGjYEUN-iB-A" points="[0, 0, -161, -75]$[0, 25, -161, -50]$[161, 25, 0, -50]$[161, 75, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MFrGUKviEfGPjbJOghg_xg" id="(0.8968253968253969,0.7936507936507936)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OnJkkKviEfGPjbJOghg_xg" id="(0.1206896551724138,0.8793103448275862)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PlrKs6vUEfGGjYEUN-iB-A" type="4001" element="_PlrKsKvUEfGGjYEUN-iB-A" source="_Pf-_AK1sEfGhg4iXH2Bxcg" target="_txaBI6viEfGPjbJOghg_xg" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PlzGgKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PlzGgavUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PlrKtKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PlrKtavUEfGGjYEUN-iB-A" points="[8, 7, -121, -266]$[104, 7, -25, -266]$[104, 268, -25, -5]$[129, 268, 0, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ph6P0K1sEfGhg4iXH2Bxcg" id="(0.9333333333333333,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gsq_gKviEfGPjbJOghg_xg" id="(0.06976744186046512,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PmMvI6vUEfGGjYEUN-iB-A" type="4001" element="_PmMvIKvUEfGGjYEUN-iB-A" source="_vSs30K1uEfGhg4iXH2Bxcg" target="_Pi3HSavUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PmNWMKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PmNWMavUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PmMvJKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PmMvJavUEfGGjYEUN-iB-A" points="[0, 0, 0, -585]$[0, 585, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RcZhAK1vEfGhg4iXH2Bxcg" id="(0.5348837209302325,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PmYVUKvUEfGGjYEUN-iB-A" type="4001" element="_PmXuQKvUEfGGjYEUN-iB-A" source="_Pi3HSavUEfGGjYEUN-iB-A" target="_Pi7YsKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PmYVU6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PmYVVKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PmYVUavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PmYVUqvUEfGGjYEUN-iB-A" points="[0, 0, -261, 0]$[261, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PmfqEqvUEfGGjYEUN-iB-A" type="4001" element="_PmfDAKvUEfGGjYEUN-iB-A" source="_Pi7YsKvUEfGGjYEUN-iB-A" target="_PjCGYKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PmfqFavUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PmgRIKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PmfqE6vUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PmfqFKvUEfGGjYEUN-iB-A" points="[0, 0, -147, 0]$[147, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pmnl4KvUEfGGjYEUN-iB-A" type="4001" element="_Pmm-0KvUEfGGjYEUN-iB-A" source="_Pgw1gKvUEfGGjYEUN-iB-A" target="_PhGzwKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PmoM8KvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PmoM8avUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pmnl4avUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pmnl4qvUEfGGjYEUN-iB-A" points="[0, 0, 0, -76]$[0, 76, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PmvhsKvUEfGGjYEUN-iB-A" type="4001" element="_Pmu6oKvUEfGGjYEUN-iB-A" source="_PhGzwKvUEfGGjYEUN-iB-A" target="_PiWJ4KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pmvhs6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PmvhtKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PmvhsavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PmvhsqvUEfGGjYEUN-iB-A" points="[-1, 25, -117, -339]$[-1, 368, -117, 4]$[39, 368, -77, 4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pm8WA6vUEfGGjYEUN-iB-A" type="4001" element="_Pm8WAKvUEfGGjYEUN-iB-A" source="_PhlU4KvUEfGGjYEUN-iB-A" target="_Ph8hQKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pm8WBqvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pm8WB6vUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pm8WBKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pm8WBavUEfGGjYEUN-iB-A" points="[0, 0, -179, 0]$[179, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PnE44KvUEfGGjYEUN-iB-A" type="4001" element="_PnER0KvUEfGGjYEUN-iB-A" source="_Ph8hQKvUEfGGjYEUN-iB-A" target="_Pho_SKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PnE446vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PnE45KvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PnE44avUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PnE44qvUEfGGjYEUN-iB-A" points="[-8, 13, -187, -122]$[-8, 110, -187, -25]$[117, 110, -62, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PnLmkKvUEfGGjYEUN-iB-A" type="4001" element="_PnK_gKvUEfGGjYEUN-iB-A" source="_Ph8hQKvUEfGGjYEUN-iB-A" target="_Ph2aoKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PnLmk6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PnLmlKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PnLmkavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PnLmkqvUEfGGjYEUN-iB-A" points="[0, 0, -107, 0]$[107, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PnTiY6vUEfGGjYEUN-iB-A" type="4001" element="_PnTiYKvUEfGGjYEUN-iB-A" source="_Ph2aoKvUEfGGjYEUN-iB-A" target="_PicQgKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PnUJcKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PnUJcavUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PnTiZKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PnTiZavUEfGGjYEUN-iB-A" points="[70, -2, -133, -553]$[195, -2, -8, -553]$[195, 520, -8, -31]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PnaQEqvUEfGGjYEUN-iB-A" type="4001" element="_PnZpAKvUEfGGjYEUN-iB-A" source="_PiM_8KvUEfGGjYEUN-iB-A" target="_PiQqXavUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_PnaQFavUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PnaQFqvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PnaQE6vUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PnaQFKvUEfGGjYEUN-iB-A" points="[0, 0, -128, 0]$[128, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e0EAcKvUEfGGjYEUN-iB-A" id="(0.07352941176470588,0.47058823529411764)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PnzRo6vUEfGGjYEUN-iB-A" type="4001" element="_PnzRoKvUEfGGjYEUN-iB-A" source="_PiCA0KvUEfGGjYEUN-iB-A" target="_PhhDdqvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pnz4sKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pnz4savUEfGGjYEUN-iB-A" x="16" y="14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PnzRpKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PnzRpavUEfGGjYEUN-iB-A" points="[-2, -5, -68, 80]$[-2, -45, -68, 40]$[68, -45, 2, 40]$[68, -81, 2, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MjYSYKxYEfG6DcibwtxsHw" id="(0.4883720930232558,0.16279069767441862)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3QDpQKxYEfG6DcibwtxsHw" id="(0.45,0.92)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pn70gKvUEfGGjYEUN-iB-A" type="4001" element="_Pn7NcKvUEfGGjYEUN-iB-A" source="_PiCA0KvUEfGGjYEUN-iB-A" target="_Pg28IKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pn70g6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pn70hKvUEfGGjYEUN-iB-A" x="6" y="-2"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pn70gavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pn70gqvUEfGGjYEUN-iB-A" points="[-17, -4, 568, 283]$[-17, -306, 568, -19]$[-420, -306, 165, -19]$[-420, -310, 165, -23]$[-556, -310, 29, -23]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2967QK1nEfGhg4iXH2Bxcg" id="(0.7661290322580645,0.8709677419354839)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EeDNoKviEfGPjbJOghg_xg" type="4001" element="_Ed-8MKviEfGPjbJOghg_xg" source="_PjLQUKvUEfGGjYEUN-iB-A" target="_PhdZGavUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EeDNo6viEfGPjbJOghg_xg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EeD0sKviEfGPjbJOghg_xg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EeDNoaviEfGPjbJOghg_xg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EeDNoqviEfGPjbJOghg_xg" points="[0, 0, -480, 350]$[451, -348, -29, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EeFC0KviEfGPjbJOghg_xg" id="(0.96,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EeFC0aviEfGPjbJOghg_xg" id="(0.19727891156462585,0.547945205479452)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5h2JUqviEfGPjbJOghg_xg" type="4001" element="_5h1iQKviEfGPjbJOghg_xg" source="_txaBI6viEfGPjbJOghg_xg" target="_PhyJOKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5h2wYKviEfGPjbJOghg_xg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5h2wYaviEfGPjbJOghg_xg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5h2JU6viEfGPjbJOghg_xg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5h2JVKviEfGPjbJOghg_xg" points="[0, -2, -96, 453]$[97, -405, 1, 50]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5h3XcKviEfGPjbJOghg_xg" id="(1.0,0.5116279069767442)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5h3XcaviEfGPjbJOghg_xg" id="(0.1056338028169014,0.5352112676056338)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7GLp4KviEfGPjbJOghg_xg" type="4001" element="_7GImkKviEfGPjbJOghg_xg" source="_txaBI6viEfGPjbJOghg_xg" target="_PicQgKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7GLp46viEfGPjbJOghg_xg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7GLp5KviEfGPjbJOghg_xg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7GLp4aviEfGPjbJOghg_xg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7GLp4qviEfGPjbJOghg_xg" points="[-22, 21, 573, 57]$[-22, 67, 573, 103]$[-566, 67, 29, 103]$[-566, -23, 29, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7GMQ8KviEfGPjbJOghg_xg" id="(1.0,0.5116279069767442)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7GMQ8aviEfGPjbJOghg_xg" id="(0.35714285714285715,0.7936507936507936)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6MRiwKxYEfG6DcibwtxsHw" type="4001" element="_6MQ7sKxYEfG6DcibwtxsHw" source="_EtxyqaxZEfG6DcibwtxsHw" target="_PiCA0KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6MSJ0axYEfG6DcibwtxsHw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6MSJ0qxYEfG6DcibwtxsHw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6MRiwaxYEfG6DcibwtxsHw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6MSJ0KxYEfG6DcibwtxsHw" points="[-69, -26, 19, 57]$[-69, -87, 19, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6MSw4KxYEfG6DcibwtxsHw" id="(1.0,0.35064935064935066)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6MSw4axYEfG6DcibwtxsHw" id="(0.2558139534883721,0.8837209302325582)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BAUQcK1sEfGhg4iXH2Bxcg" type="4001" element="_BAOJ0K1sEfGhg4iXH2Bxcg" source="_Pizc6avUEfGGjYEUN-iB-A" target="_BAG1EK1sEfGhg4iXH2Bxcg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BAVekK1sEfGhg4iXH2Bxcg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BAWFoK1sEfGhg4iXH2Bxcg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BAUQca1sEfGhg4iXH2Bxcg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BAUQcq1sEfGhg4iXH2Bxcg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RFRh0K1sEfGhg4iXH2Bxcg" type="4001" element="_RFPFkK1sEfGhg4iXH2Bxcg" source="_PiQqXavUEfGGjYEUN-iB-A" target="_Pf-_AK1sEfGhg4iXH2Bxcg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RFSI4K1sEfGhg4iXH2Bxcg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RFSI4a1sEfGhg4iXH2Bxcg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RFRh0a1sEfGhg4iXH2Bxcg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RFRh0q1sEfGhg4iXH2Bxcg" points="[11, 0, 0, 173]$[11, -163, 0, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RFVzQK1sEfGhg4iXH2Bxcg" id="(0.375,0.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RFVzQa1sEfGhg4iXH2Bxcg" id="(0.51,0.86)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Mq6vAK1vEfGhg4iXH2Bxcg" type="4001" element="_Mq450K1vEfGhg4iXH2Bxcg" source="_PhyJOKvUEfGGjYEUN-iB-A" target="_vSs30K1uEfGhg4iXH2Bxcg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Mq7WEK1vEfGhg4iXH2Bxcg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Mq7WEa1vEfGhg4iXH2Bxcg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Mq6vAa1vEfGhg4iXH2Bxcg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Mq6vAq1vEfGhg4iXH2Bxcg" points="[-106, -9, 203, -6]$[-306, -16, 3, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mq-ZYK1vEfGhg4iXH2Bxcg" id="(0.7112676056338029,0.971830985915493)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Wnz18K1vEfGhg4iXH2Bxcg" type="4001" element="_WnOnIK1vEfGhg4iXH2Bxcg" source="_vSs30K1uEfGhg4iXH2Bxcg" target="_PicQgKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Wn0dAK1vEfGhg4iXH2Bxcg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Wn0dAa1vEfGhg4iXH2Bxcg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Wnz18a1vEfGhg4iXH2Bxcg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Wnz18q1vEfGhg4iXH2Bxcg" points="[-42, -8, 677, -280]$[-689, -8, 30, -280]$[-689, 266, 30, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Wn3gUK1vEfGhg4iXH2Bxcg" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Wn3gUa1vEfGhg4iXH2Bxcg" id="(0.6587301587301587,0.09523809523809523)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
