<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_j-OAEKcREfG5hMcbx8SHTw" name="RescueSync - 1.0 - 1.0 - con descripciones" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_j_qxkKcREfG5hMcbx8SHTw" name="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_kBKmYKcREfG5hMcbx8SHTw" name="Municipio">
        <elements xmi:type="process:StartEvent" xmi:id="_kBSiMKcREfG5hMcbx8SHTw" name="Inicio" outgoing="_kEGloKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kBSiMqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kBSiMacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kBSiM6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kBfWgKcREfG5hMcbx8SHTw" name="Cargar emergencia" outgoing="_kELeIKcREfG5hMcbx8SHTw" incoming="_kEGloKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kBfWgqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kBfWgacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kBfWg6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kBfWhKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kBfWhacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kBfWhqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kBfWiKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kBfWh6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kBfWiqcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kBfWi6cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kBfWiacREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kBf9kKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kBnSUKcREfG5hMcbx8SHTw" name="Visualizar ofertas validadas" outgoing="_kEzwQKcREfG5hMcbx8SHTw" incoming="_kE2MgKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kBn5YacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kBn5YKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kBn5YqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kBn5Y6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kBn5ZKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kBn5ZacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kBn5Z6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kBn5ZqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kBn5aacREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kBn5aqcREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kBn5aKcREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kBn5a6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kBsK0KcREfG5hMcbx8SHTw" name="Seleccionar ofertas" outgoing="_kE4BsKcREfG5hMcbx8SHTw" incoming="_kEzwQKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kBsK0qcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kBsK0acREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kBsK06cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kBsK1KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kBsK1acREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kBsK1qcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kBsK2KcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kBsK16cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kBsK2qcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kBsK26cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kBsK2acREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kBsK3KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kBwcQKcREfG5hMcbx8SHTw" name="Centro coordinador regional">
        <elements xmi:type="process:Task" xmi:id="_kB170KcREfG5hMcbx8SHTw" name="Recibir y revisar emergencia" outgoing="_kEOhcKcREfG5hMcbx8SHTw" incoming="_kELeIKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kB170qcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kB170acREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kB1706cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kB171KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kB171acREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kB171qcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kB172KcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kB1716cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kB172qcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kB1726cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kB172acREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kB173KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kB5mMKcREfG5hMcbx8SHTw" name="Generar lotes de necesidades" outgoing="_kEQ9sKcREfG5hMcbx8SHTw" incoming="_kEOhcKcREfG5hMcbx8SHTw _kEu3wKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kB6NQKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kB5mMacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kB6NQacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kB6NQqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kB6NQ6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kB6NRKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kB6NRqcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kB6NRacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kB6NSKcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kB6NSacREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kB6NR6cREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kB6NSqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kB-esKcREfG5hMcbx8SHTw" name="Publicar convocatoria" outgoing="_kE6d8KcREfG5hMcbx8SHTw" incoming="_kEQ9sKcREfG5hMcbx8SHTw _kEr0cKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kB-esqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kB-esacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kB-es6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kB_FwKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kB_FwacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kB_FwqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kB_FxKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kB_Fw6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kB_FxqcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kB_Fx6cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kB_FxacREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kB_FyKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kCCJEKcREfG5hMcbx8SHTw" name="Evaluar cobertura" outgoing="_kEpYMKcREfG5hMcbx8SHTw" incoming="_kElGwKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kCCwIacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kCCwIKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kCCwIqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kCCwI6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kCCwJKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kCCwJacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kCCwJ6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kCCwJqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kCCwKacREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kCCwKqcREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kCCwKKcREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kCCwK6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_kCHBkKcREfG5hMcbx8SHTw" name="¿Qué acción tomar?" outgoing="_kEr0cKcREfG5hMcbx8SHTw _kEu3wKcREfG5hMcbx8SHTw _kExUAKcREfG5hMcbx8SHTw" incoming="_kEpYMKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kCHBkqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kCHBkacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kCHBk6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kCSnwKcREfG5hMcbx8SHTw" name="Sistema">
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_kCYuYKcREfG5hMcbx8SHTw" name="Fin de ventana de ofertas" outgoing="_kEY5gKcREfG5hMcbx8SHTw" incoming="_kE6d8KcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kCYuYqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kCYuYacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kCYuY6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kCk7oKcREfG5hMcbx8SHTw" name="Evaluar ofertas" outgoing="_kEbVwKcREfG5hMcbx8SHTw" incoming="_kEY5gKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kClisacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kClisKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kClisqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kClis6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kClitKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kClitacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kClit6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kClitqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_kCusoKcREfG5hMcbx8SHTw" name="¿Cobertura total?" outgoing="_kEeZEKcREfG5hMcbx8SHTw _kElGwKcREfG5hMcbx8SHTw" incoming="_kEbVwKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kCusoqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kCusoacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kCuso6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kC3PgKcREfG5hMcbx8SHTw" name="Enviar ofertas a Sistema Nacional" outgoing="_kEiqgKcREfG5hMcbx8SHTw" incoming="_kEeZEKcREfG5hMcbx8SHTw _kExUAKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kC32kacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kC32kKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kC32kqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kC32k6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kC32lKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kC32lacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kC32l6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kC32lqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kC7g8KcREfG5hMcbx8SHTw" name="Asignar ofertas" outgoing="_kE2MgKcREfG5hMcbx8SHTw" incoming="_kFBLoKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kC7g8qcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kC7g8acREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kC7g86cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kC7g9KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kC7g9acREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kC7g9qcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kC7g-KcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kC7g96cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kC_LUKcREfG5hMcbx8SHTw" name="Registrar adjudicación" outgoing="_kE86MKcREfG5hMcbx8SHTw" incoming="_kE4BsKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kC_LUqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kC_LUacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kC_LU6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kC_LVKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kC_LVacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kC_LVqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kC_LWKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kC_LV6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kDC1sKcREfG5hMcbx8SHTw" name="Notificar a las ONGs" outgoing="_kE_WcKcREfG5hMcbx8SHTw" incoming="_kE86MKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDDcwacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDDcwKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDDcwqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDDcw6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDDcxKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDDcxacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDDcx6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDDcxqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kDGgEKcREfG5hMcbx8SHTw" name="Enviar compromiso" outgoing="_kFDn4KcREfG5hMcbx8SHTw" incoming="_kE_WcKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDGgEqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDGgEacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDGgE6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDGgFKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDGgFacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDGgFqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDGgGKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDGgF6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kDJjYKcREfG5hMcbx8SHTw" name="Recibir estado de finalización" outgoing="_kFRqUKcREfG5hMcbx8SHTw" incoming="_kFPOEKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDJjYqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDJjYacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDJjY6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDJjZKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDJjZacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDJjZqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDJjaKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDJjZ6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kDMmsKcREfG5hMcbx8SHTw" name="Informar finalización" outgoing="_kFUGkKcREfG5hMcbx8SHTw" incoming="_kFRqUKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDMmsqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDMmsacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDMms6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDMmtKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDMmtacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDMmtqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDMmuKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDMmt6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kDPqAKcREfG5hMcbx8SHTw" name="ONG">
        <elements xmi:type="process:Task" xmi:id="_kDT7cKcREfG5hMcbx8SHTw" name="Recibir convocatoria" outgoing="_kEUBAKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDUigacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDUigKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDUigqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDUig6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDUihKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDUihacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDUih6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDUihqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDUiiacREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDUiiqcREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDUiiKcREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDUii6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kDW-wKcREfG5hMcbx8SHTw" name="Cargar oferta de ayuda" outgoing="_kEWdQKcREfG5hMcbx8SHTw" incoming="_kEUBAKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDXl0acREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDXl0KcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDXl0qcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDXl06cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDXl1KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDXl1acREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDXl16cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDXl1qcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDXl2acREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDXl2qcREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDXl2KcREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDXl26cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kDaCEKcREfG5hMcbx8SHTw" name="Modificar oferta" incoming="_kEWdQKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDaCEqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDaCEacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDaCE6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDaCFKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDaCFacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDaCFqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDaCGKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDaCF6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDaCGqcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDaCG6cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDaCGacREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDaCHKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kDdFYKcREfG5hMcbx8SHTw" name="Recibir notificación" outgoing="_kFIgYKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDdFYqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDdFYacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDdFY6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDdFZKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDdFZacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDdFZqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDdFaKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDdFZ6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDdFaqcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDdFa6cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDdFaacREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDdFbKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kDgIsKcREfG5hMcbx8SHTw" name="Desplegar recursos" outgoing="_kFKVkKcREfG5hMcbx8SHTw" incoming="_kFIgYKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDgIsqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDgIsacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDgIs6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDgItKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDgItacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDgItqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDgIuKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDgIt6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDgIuqcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDgIu6cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDgIuacREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDgIvKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kDik8KcREfG5hMcbx8SHTw" name="Ejecutar actividades" outgoing="_kFMx0KcREfG5hMcbx8SHTw" incoming="_kFKVkKcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDjMAacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDjMAKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDjMAqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDjMA6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDjMBKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDjMBacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDjMB6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDjMBqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDjMCacREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDjMCqcREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDjMCKcREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDjMC6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kDloQKcREfG5hMcbx8SHTw" name="Marcar actividades como finalizadas" outgoing="_kFPOEKcREfG5hMcbx8SHTw" incoming="_kFMx0KcREfG5hMcbx8SHTw" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDloQqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDloQacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDloQ6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDloRKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDloRacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDloRqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDloSKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDloR6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kDloSqcREfG5hMcbx8SHTw">
            <targetForm xmi:type="expression:Expression" xmi:id="_kDloS6cREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kDloSacREfG5hMcbx8SHTw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kDloTKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kDorkKcREfG5hMcbx8SHTw" name="Sistema nacional">
        <elements xmi:type="process:ServiceTask" xmi:id="_kDsV8KcREfG5hMcbx8SHTw" name="Evaluar habilitación/competencia" outgoing="_kFBLoKcREfG5hMcbx8SHTw" incoming="_kEiqgKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDsV8qcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDsV8acREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDsV86cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDsV9KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDsV9acREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDsV9qcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDsV-KcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDsV96cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kDuyMKcREfG5hMcbx8SHTw" name="Registrar compromiso de recursos" outgoing="_kFGEIKcREfG5hMcbx8SHTw" incoming="_kFDn4KcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDvZQacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDvZQKcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDvZQqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDvZQ6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDvZRKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDvZRacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDvZR6cREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDvZRqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kDx1gKcREfG5hMcbx8SHTw" name="Bloquear recursos" incoming="_kFGEIKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kDx1gqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kDx1gacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kDx1g6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kDyckKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kDyckacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kDyckqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kDyclKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kDyck6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kD1f4KcREfG5hMcbx8SHTw" name="Marcar proyecto como terminado" outgoing="_kFWi0KcREfG5hMcbx8SHTw" incoming="_kFUGkKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kD1f4qcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kD1f4acREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kD1f46cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kD1f5KcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kD1f5acREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kD1f5qcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kD1f6KcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kD1f56cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kD4jMKcREfG5hMcbx8SHTw" name="Liberar recursos" outgoing="_kFY_EKcREfG5hMcbx8SHTw" incoming="_kFWi0KcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kD4jMqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kD4jMacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kD4jM6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kD4jNKcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kD4jNacREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kD4jNqcREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kD4jOKcREfG5hMcbx8SHTw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kD4jN6cREfG5hMcbx8SHTw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_kD8NkKcREfG5hMcbx8SHTw" name="Fin" incoming="_kFY_EKcREfG5hMcbx8SHTw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kD8NkqcREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kD8NkacREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kD8Nk6cREfG5hMcbx8SHTw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_kA4SgKcREfG5hMcbx8SHTw">
        <targetForm xmi:type="expression:Expression" xmi:id="_kA4SgacREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_kA45kKcREfG5hMcbx8SHTw">
        <targetForm xmi:type="expression:Expression" xmi:id="_kA45kacREfG5hMcbx8SHTw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEGloKcREfG5hMcbx8SHTw" target="_kBfWgKcREfG5hMcbx8SHTw" source="_kBSiMKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEHMsKcREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEHMsacREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kELeIKcREfG5hMcbx8SHTw" target="_kB170KcREfG5hMcbx8SHTw" source="_kBfWgKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kELeIacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kELeIqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEOhcKcREfG5hMcbx8SHTw" target="_kB5mMKcREfG5hMcbx8SHTw" source="_kB170KcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEOhcacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEOhcqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEQ9sKcREfG5hMcbx8SHTw" target="_kB-esKcREfG5hMcbx8SHTw" source="_kB5mMKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEQ9sacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEQ9sqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEUBAKcREfG5hMcbx8SHTw" target="_kDW-wKcREfG5hMcbx8SHTw" source="_kDT7cKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEUBAacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEUBAqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEWdQKcREfG5hMcbx8SHTw" target="_kDaCEKcREfG5hMcbx8SHTw" source="_kDW-wKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEWdQacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEWdQqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEY5gKcREfG5hMcbx8SHTw" target="_kCk7oKcREfG5hMcbx8SHTw" source="_kCYuYKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEY5gacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEY5gqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEbVwKcREfG5hMcbx8SHTw" target="_kCusoKcREfG5hMcbx8SHTw" source="_kCk7oKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEb80KcREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEb80acREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEeZEKcREfG5hMcbx8SHTw" name="Si" target="_kC3PgKcREfG5hMcbx8SHTw" source="_kCusoKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEeZEacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEeZEqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEiqgKcREfG5hMcbx8SHTw" target="_kDsV8KcREfG5hMcbx8SHTw" source="_kC3PgKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEiqgacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEiqgqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kElGwKcREfG5hMcbx8SHTw" name="No" target="_kCCJEKcREfG5hMcbx8SHTw" source="_kCusoKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kElGwacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kElGwqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEpYMKcREfG5hMcbx8SHTw" target="_kCHBkKcREfG5hMcbx8SHTw" source="_kCCJEKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEpYMacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEp_QKcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEr0cKcREfG5hMcbx8SHTw" name="Reabrir convocatoria" target="_kB-esKcREfG5hMcbx8SHTw" source="_kCHBkKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEsbgKcREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEsbgacREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEu3wKcREfG5hMcbx8SHTw" name="Reformular lotes" target="_kB5mMKcREfG5hMcbx8SHTw" source="_kCHBkKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEu3wacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEu3wqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kExUAKcREfG5hMcbx8SHTw" target="_kC3PgKcREfG5hMcbx8SHTw" source="_kCHBkKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kExUAacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kExUAqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kEzwQKcREfG5hMcbx8SHTw" target="_kBsK0KcREfG5hMcbx8SHTw" source="_kBnSUKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kEzwQacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kEzwQqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kE2MgKcREfG5hMcbx8SHTw" target="_kBnSUKcREfG5hMcbx8SHTw" source="_kC7g8KcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kE2MgacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kE2MgqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kE4BsKcREfG5hMcbx8SHTw" target="_kC_LUKcREfG5hMcbx8SHTw" source="_kBsK0KcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kE4BsacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kE4BsqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kE6d8KcREfG5hMcbx8SHTw" target="_kCYuYKcREfG5hMcbx8SHTw" source="_kB-esKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kE6d8acREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kE6d8qcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kE86MKcREfG5hMcbx8SHTw" target="_kDC1sKcREfG5hMcbx8SHTw" source="_kC_LUKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kE86MacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kE86MqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kE_WcKcREfG5hMcbx8SHTw" target="_kDGgEKcREfG5hMcbx8SHTw" source="_kDC1sKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kE_WcacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kE_WcqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFBLoKcREfG5hMcbx8SHTw" target="_kC7g8KcREfG5hMcbx8SHTw" source="_kDsV8KcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFBysKcREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFBysacREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFDn4KcREfG5hMcbx8SHTw" target="_kDuyMKcREfG5hMcbx8SHTw" source="_kDGgEKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFDn4acREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFDn4qcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFGEIKcREfG5hMcbx8SHTw" target="_kDx1gKcREfG5hMcbx8SHTw" source="_kDuyMKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFGEIacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFGEIqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFIgYKcREfG5hMcbx8SHTw" target="_kDgIsKcREfG5hMcbx8SHTw" source="_kDdFYKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFIgYacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFIgYqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFKVkKcREfG5hMcbx8SHTw" target="_kDik8KcREfG5hMcbx8SHTw" source="_kDgIsKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFKVkacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFKVkqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFMx0KcREfG5hMcbx8SHTw" target="_kDloQKcREfG5hMcbx8SHTw" source="_kDik8KcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFMx0acREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFMx0qcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFPOEKcREfG5hMcbx8SHTw" target="_kDJjYKcREfG5hMcbx8SHTw" source="_kDloQKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFPOEacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFPOEqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFRqUKcREfG5hMcbx8SHTw" target="_kDMmsKcREfG5hMcbx8SHTw" source="_kDJjYKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFRqUacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFRqUqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFUGkKcREfG5hMcbx8SHTw" target="_kD1f4KcREfG5hMcbx8SHTw" source="_kDMmsKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFUtoKcREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFUtoacREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFWi0KcREfG5hMcbx8SHTw" target="_kD4jMKcREfG5hMcbx8SHTw" source="_kD1f4KcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFWi0acREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFWi0qcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFY_EKcREfG5hMcbx8SHTw" target="_kD8NkKcREfG5hMcbx8SHTw" source="_kD4jMKcREfG5hMcbx8SHTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFY_EacREfG5hMcbx8SHTw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFY_EqcREfG5hMcbx8SHTw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_kA45kqcREfG5hMcbx8SHTw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kA3rcKcREfG5hMcbx8SHTw">
        <name xmi:type="expression:Expression" xmi:id="_kA3rcacREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kA3rcqcREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kA3rc6cREfG5hMcbx8SHTw">
        <name xmi:type="expression:Expression" xmi:id="_kA3rdKcREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kA3rdacREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kA3rdqcREfG5hMcbx8SHTw">
        <name xmi:type="expression:Expression" xmi:id="_kA3rd6cREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kA3reKcREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kA3reacREfG5hMcbx8SHTw">
        <name xmi:type="expression:Expression" xmi:id="_kA3reqcREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kA3re6cREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kA3rfKcREfG5hMcbx8SHTw">
        <name xmi:type="expression:Expression" xmi:id="_kA3rfacREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kA3rfqcREfG5hMcbx8SHTw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_j-P1QKcREfG5hMcbx8SHTw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_j-P1QacREfG5hMcbx8SHTw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_j-P1QqcREfG5hMcbx8SHTw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_j-P1Q6cREfG5hMcbx8SHTw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_j-P1RKcREfG5hMcbx8SHTw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_j-P1RacREfG5hMcbx8SHTw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_j-P1RqcREfG5hMcbx8SHTw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_j-P1R6cREfG5hMcbx8SHTw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_j-QcUKcREfG5hMcbx8SHTw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_j-OnIKcREfG5hMcbx8SHTw" type="Process" element="_j-OAEKcREfG5hMcbx8SHTw" name="RescueSync - 1.0 - 1.0 - con descripciones" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_kA6uwKcREfG5hMcbx8SHTw" type="2007" element="_j_qxkKcREfG5hMcbx8SHTw">
      <children xmi:type="notation:DecorationNode" xmi:id="_kA7V0KcREfG5hMcbx8SHTw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_kA7V0acREfG5hMcbx8SHTw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_kBLNcKcREfG5hMcbx8SHTw" type="3007" element="_kBKmYKcREfG5hMcbx8SHTw">
          <children xmi:type="notation:DecorationNode" xmi:id="_kBL0gKcREfG5hMcbx8SHTw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kBL0gacREfG5hMcbx8SHTw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kBTwUKcREfG5hMcbx8SHTw" type="3002" element="_kBSiMKcREfG5hMcbx8SHTw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kBTwUqcREfG5hMcbx8SHTw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kBTwU6cREfG5hMcbx8SHTw" x="-14" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kBTwUacREfG5hMcbx8SHTw" x="120" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kBhywKcREfG5hMcbx8SHTw" type="3005" element="_kBfWgKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kBhywqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kBhywacREfG5hMcbx8SHTw" x="220" y="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kBogcKcREfG5hMcbx8SHTw" type="3005" element="_kBnSUKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kBogcqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kBogcacREfG5hMcbx8SHTw" x="1524" y="48"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kBsx4KcREfG5hMcbx8SHTw" type="3005" element="_kBsK0KcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kBsx4qcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kBsx4acREfG5hMcbx8SHTw" x="1752" y="48"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kBLNcacREfG5hMcbx8SHTw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kBLNcqcREfG5hMcbx8SHTw" fontName="Cantarell"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kBLNc6cREfG5hMcbx8SHTw" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kBL0gqcREfG5hMcbx8SHTw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kBLNdKcREfG5hMcbx8SHTw" x="672" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kBxDUKcREfG5hMcbx8SHTw" type="3007" element="_kBwcQKcREfG5hMcbx8SHTw">
          <children xmi:type="notation:DecorationNode" xmi:id="_kBxDVacREfG5hMcbx8SHTw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kBxDVqcREfG5hMcbx8SHTw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kB2i4KcREfG5hMcbx8SHTw" type="3005" element="_kB170KcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kB2i4qcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kB2i4acREfG5hMcbx8SHTw" x="220" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kB60UKcREfG5hMcbx8SHTw" type="3005" element="_kB5mMKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kB60UqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kB60UacREfG5hMcbx8SHTw" x="406" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kB_s0KcREfG5hMcbx8SHTw" type="3005" element="_kB-esKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kB_s0qcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kB_s0acREfG5hMcbx8SHTw" x="615" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kCDXMKcREfG5hMcbx8SHTw" type="3005" element="_kCCJEKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kCDXMqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCDXMacREfG5hMcbx8SHTw" x="824" y="159"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kCHooKcREfG5hMcbx8SHTw" type="3009" element="_kCHBkKcREfG5hMcbx8SHTw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kCIPsKcREfG5hMcbx8SHTw" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kCIPsacREfG5hMcbx8SHTw" x="-89" y="47"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCHooacREfG5hMcbx8SHTw" x="852" y="53"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kBxDUacREfG5hMcbx8SHTw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kBxDUqcREfG5hMcbx8SHTw" fontName="Cantarell"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kBxDU6cREfG5hMcbx8SHTw" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kBxDV6cREfG5hMcbx8SHTw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kBxDVKcREfG5hMcbx8SHTw" x="3855" y="125" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kCTO0KcREfG5hMcbx8SHTw" type="3007" element="_kCSnwKcREfG5hMcbx8SHTw">
          <children xmi:type="notation:DecorationNode" xmi:id="_kCTO1acREfG5hMcbx8SHTw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kCTO1qcREfG5hMcbx8SHTw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kCZVcKcREfG5hMcbx8SHTw" type="3017" element="_kCYuYKcREfG5hMcbx8SHTw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kCZ8gKcREfG5hMcbx8SHTw" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kCZ8gacREfG5hMcbx8SHTw" x="-154" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCZVcacREfG5hMcbx8SHTw" x="671" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kCmJwKcREfG5hMcbx8SHTw" type="3027" element="_kCk7oKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kCmJwqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCmJwacREfG5hMcbx8SHTw" x="852" y="130"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kCvTsKcREfG5hMcbx8SHTw" type="3008" element="_kCusoKcREfG5hMcbx8SHTw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kCvTsqcREfG5hMcbx8SHTw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kCvTs6cREfG5hMcbx8SHTw" x="-84" y="31"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCvTsacREfG5hMcbx8SHTw" x="1067" y="133"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kC32mKcREfG5hMcbx8SHTw" type="3027" element="_kC3PgKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kC32mqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kC32macREfG5hMcbx8SHTw" x="1241" y="121"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kC8IAKcREfG5hMcbx8SHTw" type="3027" element="_kC7g8KcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kC8IAqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kC8IAacREfG5hMcbx8SHTw" x="1525" y="209"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kC_yYKcREfG5hMcbx8SHTw" type="3027" element="_kC_LUKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kC_yYqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kC_yYacREfG5hMcbx8SHTw" x="1747" y="209"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDDcyKcREfG5hMcbx8SHTw" type="3027" element="_kDC1sKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDDcyqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDDcyacREfG5hMcbx8SHTw" x="2002" y="206"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDGgGacREfG5hMcbx8SHTw" type="3027" element="_kDGgEKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDHHIacREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDHHIKcREfG5hMcbx8SHTw" x="2240" y="215"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDJjaacREfG5hMcbx8SHTw" type="3027" element="_kDJjYKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDKKcKcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDJjaqcREfG5hMcbx8SHTw" x="2834" y="145"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDMmuacREfG5hMcbx8SHTw" type="3027" element="_kDMmsKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDNNwKcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDMmuqcREfG5hMcbx8SHTw" x="3047" y="150"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kCTO0acREfG5hMcbx8SHTw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kCTO0qcREfG5hMcbx8SHTw" fontName="Cantarell"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kCTO06cREfG5hMcbx8SHTw" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kCT14KcREfG5hMcbx8SHTw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCTO1KcREfG5hMcbx8SHTw" x="3855" y="125" height="352"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kDPqAacREfG5hMcbx8SHTw" type="3007" element="_kDPqAKcREfG5hMcbx8SHTw">
          <children xmi:type="notation:DecorationNode" xmi:id="_kDQREKcREfG5hMcbx8SHTw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kDQREacREfG5hMcbx8SHTw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kDUijKcREfG5hMcbx8SHTw" type="3005" element="_kDT7cKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDVJkKcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDUijacREfG5hMcbx8SHTw" x="220" y="126"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDXl3KcREfG5hMcbx8SHTw" type="3005" element="_kDW-wKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDXl3qcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDXl3acREfG5hMcbx8SHTw" x="425" y="126"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDapIKcREfG5hMcbx8SHTw" type="3005" element="_kDaCEKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDapIqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDapIacREfG5hMcbx8SHTw" x="647" y="131"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDdscKcREfG5hMcbx8SHTw" type="3005" element="_kDdFYKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDdscqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDdscacREfG5hMcbx8SHTw" x="2010" y="154"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDgIvacREfG5hMcbx8SHTw" type="3005" element="_kDgIsKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDgvwKcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDgIvqcREfG5hMcbx8SHTw" x="2407" y="173"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDjMDKcREfG5hMcbx8SHTw" type="3005" element="_kDik8KcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDjMDqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDjMDacREfG5hMcbx8SHTw" x="2579" y="168"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDmPUKcREfG5hMcbx8SHTw" type="3005" element="_kDloQKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDmPUqcREfG5hMcbx8SHTw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDmPUacREfG5hMcbx8SHTw" x="2800" y="156"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kDPqAqcREfG5hMcbx8SHTw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kDPqA6cREfG5hMcbx8SHTw" fontName="Cantarell"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kDPqBKcREfG5hMcbx8SHTw" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kDQREqcREfG5hMcbx8SHTw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDPqBacREfG5hMcbx8SHTw" x="3855" y="125" height="329"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kDorkacREfG5hMcbx8SHTw" type="3007" element="_kDorkKcREfG5hMcbx8SHTw">
          <children xmi:type="notation:DecorationNode" xmi:id="_kDorlqcREfG5hMcbx8SHTw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kDorl6cREfG5hMcbx8SHTw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kDs9AKcREfG5hMcbx8SHTw" type="3027" element="_kDsV8KcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDs9AqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDs9AacREfG5hMcbx8SHTw" x="1241" y="97"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDvZSKcREfG5hMcbx8SHTw" type="3027" element="_kDuyMKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDvZSqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDvZSacREfG5hMcbx8SHTw" x="2236" y="137"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kDyclacREfG5hMcbx8SHTw" type="3027" element="_kDx1gKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kDycl6cREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDyclqcREfG5hMcbx8SHTw" x="2492" y="142"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kD2G8KcREfG5hMcbx8SHTw" type="3027" element="_kD1f4KcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kD2G8qcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kD2G8acREfG5hMcbx8SHTw" x="2998" y="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kD5KQKcREfG5hMcbx8SHTw" type="3027" element="_kD4jMKcREfG5hMcbx8SHTw" fontName="Cantarell" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kD5KQqcREfG5hMcbx8SHTw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kD5KQacREfG5hMcbx8SHTw" x="3359" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kD80oKcREfG5hMcbx8SHTw" type="3003" element="_kD8NkKcREfG5hMcbx8SHTw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kD80oqcREfG5hMcbx8SHTw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kD80o6cREfG5hMcbx8SHTw" x="8" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kD80oacREfG5hMcbx8SHTw" x="3606" y="115"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kDorkqcREfG5hMcbx8SHTw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kDork6cREfG5hMcbx8SHTw" fontName="Cantarell"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kDorlKcREfG5hMcbx8SHTw" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kDormKcREfG5hMcbx8SHTw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kDorlacREfG5hMcbx8SHTw" x="3855" y="125" height="271"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_kA6uwacREfG5hMcbx8SHTw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_kA6uwqcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_kA6uw6cREfG5hMcbx8SHTw" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_kA7V0qcREfG5hMcbx8SHTw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kA6uxKcREfG5hMcbx8SHTw" width="3850" height="1517"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_j-OnIacREfG5hMcbx8SHTw"/>
    <edges xmi:type="notation:Connector" xmi:id="_kEHzwKcREfG5hMcbx8SHTw" type="4001" element="_kEGloKcREfG5hMcbx8SHTw" source="_kBTwUKcREfG5hMcbx8SHTw" target="_kBhywKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEHzw6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEHzxKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEHzwacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEHzwqcREfG5hMcbx8SHTw" points="[0, 0, -70, 0]$[70, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEMFMKcREfG5hMcbx8SHTw" type="4001" element="_kELeIKcREfG5hMcbx8SHTw" source="_kBhywKcREfG5hMcbx8SHTw" target="_kB2i4KcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEMFM6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEMFNKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEMFMacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEMFMqcREfG5hMcbx8SHTw" points="[0, 0, 0, -229]$[0, 229, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEOhc6cREfG5hMcbx8SHTw" type="4001" element="_kEOhcKcREfG5hMcbx8SHTw" source="_kB2i4KcREfG5hMcbx8SHTw" target="_kB60UKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEPIgKcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEPIgacREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEOhdKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEOhdacREfG5hMcbx8SHTw" points="[0, 0, -68, 0]$[68, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kERkwKcREfG5hMcbx8SHTw" type="4001" element="_kEQ9sKcREfG5hMcbx8SHTw" source="_kB60UKcREfG5hMcbx8SHTw" target="_kB_s0KcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kERkw6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kERkxKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kERkwacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kERkwqcREfG5hMcbx8SHTw" points="[0, 0, -83, 0]$[83, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEUBA6cREfG5hMcbx8SHTw" type="4001" element="_kEUBAKcREfG5hMcbx8SHTw" source="_kDUijKcREfG5hMcbx8SHTw" target="_kDXl3KcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEUBBqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEUBB6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEUBBKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEUBBacREfG5hMcbx8SHTw" points="[0, 0, -85, 0]$[85, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEWdQ6cREfG5hMcbx8SHTw" type="4001" element="_kEWdQKcREfG5hMcbx8SHTw" source="_kDXl3KcREfG5hMcbx8SHTw" target="_kDapIKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEWdRqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEWdR6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEWdRKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEWdRacREfG5hMcbx8SHTw" points="[0, 0, -98, 0]$[98, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEZgkKcREfG5hMcbx8SHTw" type="4001" element="_kEY5gKcREfG5hMcbx8SHTw" source="_kCZVcKcREfG5hMcbx8SHTw" target="_kCmJwKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEZgk6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEZglKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEZgkacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEZgkqcREfG5hMcbx8SHTw" points="[0, 0, -151, 0]$[151, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEb80qcREfG5hMcbx8SHTw" type="4001" element="_kEbVwKcREfG5hMcbx8SHTw" source="_kCmJwKcREfG5hMcbx8SHTw" target="_kCvTsKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEb81acREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEb81qcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEb806cREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEb81KcREfG5hMcbx8SHTw" points="[0, 0, -115, 0]$[115, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEfnMKcREfG5hMcbx8SHTw" type="4001" element="_kEeZEKcREfG5hMcbx8SHTw" source="_kCvTsKcREfG5hMcbx8SHTw" target="_kC32mKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEfnM6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEfnNKcREfG5hMcbx8SHTw" x="-14" y="-26"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEfnMacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEfnMqcREfG5hMcbx8SHTw" points="[0, 0, -131, 0]$[131, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEiqg6cREfG5hMcbx8SHTw" type="4001" element="_kEiqgKcREfG5hMcbx8SHTw" source="_kC32mKcREfG5hMcbx8SHTw" target="_kDs9AKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEiqhqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEjRkKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEiqhKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEiqhacREfG5hMcbx8SHTw" points="[0, 0, 0, -590]$[0, 590, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEm78KcREfG5hMcbx8SHTw" type="4001" element="_kElGwKcREfG5hMcbx8SHTw" source="_kCvTsKcREfG5hMcbx8SHTw" target="_kCDXMKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEm786cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEm79KcREfG5hMcbx8SHTw" x="16" y="-24"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEm78acREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEm78qcREfG5hMcbx8SHTw" points="[0, 0, 162, 192]$[0, -192, 162, 0]$[-162, -192, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEp_QacREfG5hMcbx8SHTw" type="4001" element="_kEpYMKcREfG5hMcbx8SHTw" source="_kCDXMKcREfG5hMcbx8SHTw" target="_kCHooKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEp_RKcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEp_RacREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEp_QqcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEp_Q6cREfG5hMcbx8SHTw" points="[0, 0, 0, 63]$[0, -63, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEsbgqcREfG5hMcbx8SHTw" type="4001" element="_kEr0cKcREfG5hMcbx8SHTw" source="_kCHooKcREfG5hMcbx8SHTw" target="_kB_s0KcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEsbhacREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEsbhqcREfG5hMcbx8SHTw" x="148" y="6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEsbg6cREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEsbhKcREfG5hMcbx8SHTw" points="[0, 0, 170, -30]$[-170, 0, 0, -30]$[-170, 30, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEu3w6cREfG5hMcbx8SHTw" type="4001" element="_kEu3wKcREfG5hMcbx8SHTw" source="_kCHooKcREfG5hMcbx8SHTw" target="_kB60UKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEu3xqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEu3x6cREfG5hMcbx8SHTw" x="116" y="6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEu3xKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEu3xacREfG5hMcbx8SHTw" points="[0, 0, 404, -49]$[-404, 0, 0, -49]$[-404, 49, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEx7EKcREfG5hMcbx8SHTw" type="4001" element="_kExUAKcREfG5hMcbx8SHTw" source="_kCHooKcREfG5hMcbx8SHTw" target="_kC32mKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEx7E6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEx7FKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEx7EacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEx7EqcREfG5hMcbx8SHTw" points="[0, 0, -407, -301]$[407, 0, 0, -301]$[407, 301, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kEzwQ6cREfG5hMcbx8SHTw" type="4001" element="_kEzwQKcREfG5hMcbx8SHTw" source="_kBogcKcREfG5hMcbx8SHTw" target="_kBsx4KcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kEzwRqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kEzwR6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kEzwRKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kEzwRacREfG5hMcbx8SHTw" points="[0, 0, -106, 0]$[106, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kE2Mg6cREfG5hMcbx8SHTw" type="4001" element="_kE2MgKcREfG5hMcbx8SHTw" source="_kC8IAKcREfG5hMcbx8SHTw" target="_kBogcKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kE2MhqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kE2Mh6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kE2MhKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kE2MhacREfG5hMcbx8SHTw" points="[0, 0, 0, 600]$[0, -600, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kE4owKcREfG5hMcbx8SHTw" type="4001" element="_kE4BsKcREfG5hMcbx8SHTw" source="_kBsx4KcREfG5hMcbx8SHTw" target="_kC_yYKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kE4ow6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kE4oxKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kE4owacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kE4owqcREfG5hMcbx8SHTw" points="[0, 0, 0, -595]$[0, 595, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kE7FAKcREfG5hMcbx8SHTw" type="4001" element="_kE6d8KcREfG5hMcbx8SHTw" source="_kB_s0KcREfG5hMcbx8SHTw" target="_kCZVcKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kE7FA6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kE7FBKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kE7FAacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kE7FAqcREfG5hMcbx8SHTw" points="[0, 0, 0, -230]$[0, 230, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kE86M6cREfG5hMcbx8SHTw" type="4001" element="_kE86MKcREfG5hMcbx8SHTw" source="_kC_yYKcREfG5hMcbx8SHTw" target="_kDDcyKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kE86NqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kE86N6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kE86NKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kE86NacREfG5hMcbx8SHTw" points="[0, 0, -133, 0]$[133, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kE_Wc6cREfG5hMcbx8SHTw" type="4001" element="_kE_WcKcREfG5hMcbx8SHTw" source="_kDDcyKcREfG5hMcbx8SHTw" target="_kDGgGacREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kE_WdqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kE_Wd6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kE_WdKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kE_WdacREfG5hMcbx8SHTw" points="[0, 0, -128, 0]$[128, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFBysqcREfG5hMcbx8SHTw" type="4001" element="_kFBLoKcREfG5hMcbx8SHTw" source="_kDs9AKcREfG5hMcbx8SHTw" target="_kC8IAKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFBytacREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFBytqcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFBys6cREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFBytKcREfG5hMcbx8SHTw" points="[0, 0, -131, 543]$[131, 0, 0, 543]$[131, -543, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFEO8KcREfG5hMcbx8SHTw" type="4001" element="_kFDn4KcREfG5hMcbx8SHTw" source="_kDGgGacREfG5hMcbx8SHTw" target="_kDvZSKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFEO86cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFEO9KcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFEO8acREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFEO8qcREfG5hMcbx8SHTw" points="[0, 0, 0, -546]$[0, 546, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFGEI6cREfG5hMcbx8SHTw" type="4001" element="_kFGEIKcREfG5hMcbx8SHTw" source="_kDvZSKcREfG5hMcbx8SHTw" target="_kDyclacREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFGrMKcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFGrMacREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFGEJKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFGEJacREfG5hMcbx8SHTw" points="[0, 0, -132, 0]$[132, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFIgY6cREfG5hMcbx8SHTw" type="4001" element="_kFIgYKcREfG5hMcbx8SHTw" source="_kDdscKcREfG5hMcbx8SHTw" target="_kDgIvacREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFIgZqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFIgZ6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFIgZKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFIgZacREfG5hMcbx8SHTw" points="[0, 0, -267, 0]$[267, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFK8oKcREfG5hMcbx8SHTw" type="4001" element="_kFKVkKcREfG5hMcbx8SHTw" source="_kDgIvacREfG5hMcbx8SHTw" target="_kDjMDKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFK8o6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFK8pKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFK8oacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFK8oqcREfG5hMcbx8SHTw" points="[0, 0, -72, 0]$[72, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFMx06cREfG5hMcbx8SHTw" type="4001" element="_kFMx0KcREfG5hMcbx8SHTw" source="_kDjMDKcREfG5hMcbx8SHTw" target="_kDmPUKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFNY4KcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFNY4acREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFMx1KcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFMx1acREfG5hMcbx8SHTw" points="[0, 0, -97, 0]$[97, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFPOE6cREfG5hMcbx8SHTw" type="4001" element="_kFPOEKcREfG5hMcbx8SHTw" source="_kDmPUKcREfG5hMcbx8SHTw" target="_kDJjaacREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFPOFqcREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFPOF6cREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFPOFKcREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFPOFacREfG5hMcbx8SHTw" points="[0, 0, 0, 295]$[0, -295, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFSRYKcREfG5hMcbx8SHTw" type="4001" element="_kFRqUKcREfG5hMcbx8SHTw" source="_kDJjaacREfG5hMcbx8SHTw" target="_kDMmuacREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFSRY6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFSRZKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFSRYacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFSRYqcREfG5hMcbx8SHTw" points="[0, 0, -77, 0]$[77, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFUtoqcREfG5hMcbx8SHTw" type="4001" element="_kFUGkKcREfG5hMcbx8SHTw" source="_kDMmuacREfG5hMcbx8SHTw" target="_kD2G8KcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFUtpacREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFUtpqcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFUto6cREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFUtpKcREfG5hMcbx8SHTw" points="[0, 0, 0, -563]$[0, 563, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFXJ4KcREfG5hMcbx8SHTw" type="4001" element="_kFWi0KcREfG5hMcbx8SHTw" source="_kD2G8KcREfG5hMcbx8SHTw" target="_kD5KQKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFXJ46cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFXJ5KcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFXJ4acREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFXJ4qcREfG5hMcbx8SHTw" points="[0, 0, -201, 0]$[201, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFZmIKcREfG5hMcbx8SHTw" type="4001" element="_kFY_EKcREfG5hMcbx8SHTw" source="_kD5KQKcREfG5hMcbx8SHTw" target="_kD80oKcREfG5hMcbx8SHTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFZmI6cREfG5hMcbx8SHTw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFZmJKcREfG5hMcbx8SHTw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFZmIacREfG5hMcbx8SHTw" fontName="Cantarell"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFZmIqcREfG5hMcbx8SHTw" points="[0, 0, -147, 0]$[147, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
