<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_PccWMKvUEfGGjYEUN-iB-A" name="RescueSync" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_PdZ_gKvUEfGGjYEUN-iB-A" name="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_PflJwKvUEfGGjYEUN-iB-A" name="Municipio" actor="_6KsysKvaEfGGjYEUN-iB-A">
        <elements xmi:type="process:StartEvent" xmi:id="_Pfx-EKvUEfGGjYEUN-iB-A" name="Cargar emergencia" outgoing="_aaaaYLjfEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PfylIavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PfylIKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PfylIqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PgS7cKvUEfGGjYEUN-iB-A" name="Seleccionar ofertas" outgoing="_gd8UALjoEfGlPdn3R72URQ" incoming="_PnzRoKvUEfGGjYEUN-iB-A _Pk0PEKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PgTigavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PgTigKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PgTigqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_wRV7ULjoEfGlPdn3R72URQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wRV7UbjoEfGlPdn3R72URQ" name="adjudicacionId" content="adjudicacionId" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_wo-YMLjoEfGlPdn3R72URQ" name="adjudicacionId" dataType="_PcgnpKvUEfGGjYEUN-iB-A"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wRV7UrjoEfGlPdn3R72URQ" name="adjudicacionIdInput" content="adjudicacionIdInput" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xAaAwLjoEfGlPdn3R72URQ" name="adjudicacionIdInput">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_xAaAwbjoEfGlPdn3R72URQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wRV7U7joEfGlPdn3R72URQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PgTig6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PgTihKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PgTihavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PgTih6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PgTihqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PgTiiavUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_0bgHoLumEfG4kNqMMwVcrQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PgTiiKvUEfGGjYEUN-iB-A">
            <inputs xmi:type="process:ContractInput" xmi:id="_sv3YoLjoEfGlPdn3R72URQ" name="adjudicacionIdInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_sv3YobjoEfGlPdn3R72URQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PgTii6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PgZCEKvUEfGGjYEUN-iB-A" name="Centro coordinador regional" actor="_FfUhkKvbEfGGjYEUN-iB-A">
        <elements xmi:type="process:Task" xmi:id="_Pg2VEKvUEfGGjYEUN-iB-A" name="Decidir accion ante cobertura insuficiente" outgoing="_PkhUIKvUEfGGjYEUN-iB-A" incoming="_Pn7NcKvUEfGGjYEUN-iB-A" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pg2VEqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pg2VEavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pg2VE6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_TwmbgLjkEfGlPdn3R72URQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_TwmbgbjkEfGlPdn3R72URQ" name="decisionCobertura" content="decisionCobertura" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_UWtZQLjkEfGlPdn3R72URQ" name="decisionCobertura" dataType="_PcgnpKvUEfGGjYEUN-iB-A"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_TwmbgrjkEfGlPdn3R72URQ" name="decisionCoberturaInput" content="decisionCoberturaInput" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_VzybQLjkEfGlPdn3R72URQ" name="decisionCoberturaInput">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_VzybQbjkEfGlPdn3R72URQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Twmbg7jkEfGlPdn3R72URQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pg2VFKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pg2VFavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pg2VFqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pg2VGKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pg2VF6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Pg2VGqvUEfGGjYEUN-iB-A">
            <targetForm xmi:type="expression:Expression" xmi:id="_0bgHobumEfG4kNqMMwVcrQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Pg2VGavUEfGGjYEUN-iB-A">
            <inputs xmi:type="process:ContractInput" xmi:id="_PFeJILjkEfGlPdn3R72URQ" name="decisionCoberturaInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_PFeJIbjkEfGlPdn3R72URQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Pg2VHKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Pg8bsKvUEfGGjYEUN-iB-A" name="¿Qué acción tomar?" outgoing="_Pk0PEKvUEfGGjYEUN-iB-A _ARtkcLjlEfGlPdn3R72URQ" incoming="_PkhUIKvUEfGGjYEUN-iB-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pg9CwavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pg9CwKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pg9CwqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SjwnMLjfEfGlPdn3R72URQ" name="Gestionar emergencia y publicar convocatoria" outgoing="_e_JUYLjgEfGlPdn3R72URQ" incoming="_aaaaYLjfEfGlPdn3R72URQ _ARtkcLjlEfGlPdn3R72URQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SjzqgbjfEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SjzqgLjfEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SjzqgrjfEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_C159sLuREfGrDIdYaw4B4g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_C159sbuREfGrDIdYaw4B4g" name="fechaCierre" content="fechaCierre" type="TYPE_VARIABLE" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_DZM4ALuREfGrDIdYaw4B4g" name="fechaCierre" dataType="_PcgnoKvUEfGGjYEUN-iB-A"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_C159sruREfGrDIdYaw4B4g" name="parsearFechaCierre" content="java.util.Date.from(java.time.OffsetDateTime.parse(timerInput).toInstant())&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4T0CgLuREfGrDIdYaw4B4g" name="timerInput">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_4T0CgbuREfGrDIdYaw4B4g"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_C159s7uREfGrDIdYaw4B4g" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Sjzqg7jfEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SjzqhLjfEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SjzqhbjfEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Sjzqh7jfEfGlPdn3R72URQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SjzqhrjfEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Sj0RkbjfEfGlPdn3R72URQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_0bgHorumEfG4kNqMMwVcrQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Sj0RkLjfEfGlPdn3R72URQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_-Zs4ILuQEfGrDIdYaw4B4g" name="timerInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_-ZtfMLuQEfGrDIdYaw4B4g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Sj0Rk7jfEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_YhNmoLjrEfGlPdn3R72URQ" name="Monitorear ejecucion" outgoing="_JvfpULjsEfGlPdn3R72URQ" incoming="_8TEgcLjrEfGlPdn3R72URQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pf8iwK1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pf77sK1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pf8iwa1sEfGhg4iXH2Bxcg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pf8iwq1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pf8iw61sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pf8ixK1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pf8ixq1sEfGhg4iXH2Bxcg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pf8ixa1sEfGhg4iXH2Bxcg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_YhONubjrEfGlPdn3R72URQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_0bgHo7umEfG4kNqMMwVcrQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_YhONuLjrEfGlPdn3R72URQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_YhONu7jrEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PhMTUKvUEfGGjYEUN-iB-A" name="Sistema" actor="_FfUhkKvbEfGGjYEUN-iB-A">
        <elements xmi:type="process:ServiceTask" xmi:id="_PhdZEKvUEfGGjYEUN-iB-A" name="Enviar ofertas a Sistema Nacional" outgoing="_7wREcLjiEfGlPdn3R72URQ" incoming="_7VKHsLjgEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PhdZEqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PhdZEavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PhdZE6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PhdZFKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PhdZFavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PhdZFqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PhdZGKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PhdZF6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PhoYMKvUEfGGjYEUN-iB-A" name="Enviar compromiso" outgoing="_LLktILjpEfGlPdn3R72URQ" incoming="_gd8UALjoEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pho_QavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pho_QKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pho_QqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pho_Q6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pho_RKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pho_RavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pho_R6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pho_RqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_PhxiIKvUEfGGjYEUN-iB-A" name="Informar finalización" outgoing="_fQyAgLjsEfGlPdn3R72URQ" incoming="_WS9J4LjsEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PhyJMavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PhyJMKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PhyJMqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PhyJM6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PhyJNKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PhyJNavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PhyJN6vUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PhyJNqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Ph1zkKvUEfGGjYEUN-iB-A" name="Enviar Notificacion Formal" outgoing="_77ML8LjrEfGlPdn3R72URQ" incoming="_LLktILjpEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ph1zkqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ph1zkavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ph1zk6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ph1zlKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ph1zlavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ph1zlqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ph1zmKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ph1zl6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_PiBZwKvUEfGGjYEUN-iB-A" name="¿Alcanzan las cantidades?" outgoing="_PnzRoKvUEfGGjYEUN-iB-A _Pn7NcKvUEfGGjYEUN-iB-A" incoming="_6MQ7sKxYEfG6DcibwtxsHw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiBZwqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiBZwavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiBZw6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_EtxyoKxZEfG6DcibwtxsHw" name="Evaluar cantidades habilitadas" outgoing="_6MQ7sKxYEfG6DcibwtxsHw" incoming="_7wREcLjiEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GkbnsaxYEfG6DcibwtxsHw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GkbnsKxYEfG6DcibwtxsHw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GkbnsqxYEfG6DcibwtxsHw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Gkbns6xYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GkbntKxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GkbntaxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GkcOwKxYEfG6DcibwtxsHw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GkbntqxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_eksNALjgEfGlPdn3R72URQ" name="Esperar cierre de ofertas" outgoing="_-XpoULjgEfGlPdn3R72URQ" incoming="_e_JUYLjgEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eksNArjgEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eksNAbjgEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eksNA7jgEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_EeKTkLjhEfGlPdn3R72URQ" name="fechaCierre" content="fechaCierre" type="TYPE_VARIABLE" returnType="java.util.Date">
            <referencedElements xmi:type="process:Data" xmi:id="_N_cd8LuREfGrDIdYaw4B4g" name="fechaCierre" dataType="_PcgnoKvUEfGGjYEUN-iB-A"/>
          </condition>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_9a2B0LjgEfGlPdn3R72URQ" name="Obtener ofertas" outgoing="_7VKHsLjgEfGlPdn3R72URQ" incoming="_-XpoULjgEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiU7wqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiU7wavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiU7w6vUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_HAMzkKvdEfGGjYEUN-iB-A" name="tiempoTerminado" dataType="_PcgAkKvUEfGGjYEUN-iB-A">
            <defaultValue xmi:type="expression:Expression" xmi:id="_HAMzkavdEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean"/>
          </data>
          <data xmi:type="process:JavaObjectData" xmi:id="_a6szIKvdEfGGjYEUN-iB-A" name="tiempoEspera" dataType="_PcgnpavUEfGGjYEUN-iB-A" className="java.time.Duration">
            <defaultValue xmi:type="expression:Expression" xmi:id="_a6szIavdEfGGjYEUN-iB-A" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.Duration"/>
          </data>
          <data xmi:type="process:Data" xmi:id="_i92xQKvdEfGGjYEUN-iB-A" name="ventanaDeCarga" dataType="_PcgnoqvUEfGGjYEUN-iB-A">
            <defaultValue xmi:type="expression:Expression" xmi:id="_i92xQavdEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Long"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PiU7xKvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PiU7xavUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PiU7xqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PiU7yKvUEfGGjYEUN-iB-A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PiU7x6vUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_66GiYLjrEfGlPdn3R72URQ" name="Iniciar ejecucion y monitoreo" outgoing="_8TEgcLjrEfGlPdn3R72URQ _8zRDcLjrEfGlPdn3R72URQ" incoming="_77ML8LjrEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_66GiYrjrEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_66GiYbjrEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_66GiY7jrEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_JMvhkLjsEfGlPdn3R72URQ" name="¿Ejecucion y monitoreo finalizados?" outgoing="_WS9J4LjsEfGlPdn3R72URQ" incoming="_JvfpULjsEfGlPdn3R72URQ _KGhCMLjsEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JMvhkrjsEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JMvhkbjsEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JMvhk7jsEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_PjA4QKvUEfGGjYEUN-iB-A" name="Fin" incoming="_fQyAgLjsEfGlPdn3R72URQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PjBfUavUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PjBfUKvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PjBfUqvUEfGGjYEUN-iB-A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PiGSQKvUEfGGjYEUN-iB-A" name="ONGs" actor="_SeZAEKvbEfGGjYEUN-iB-A">
        <elements xmi:type="process:Task" xmi:id="_2GDaALjqEfGlPdn3R72URQ" name="Ejecutar y finalizar actividades" outgoing="_KGhCMLjsEfGlPdn3R72URQ" incoming="_8zRDcLjrEfGlPdn3R72URQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2GEBEbjqEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2GEBELjqEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2GEBErjqEfGlPdn3R72URQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2GEBE7jqEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2GEBFLjqEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2GEBFbjqEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2GEBF7jqEfGlPdn3R72URQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2GEBFrjqEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_2GEBGbjqEfGlPdn3R72URQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_0bgHpLumEfG4kNqMMwVcrQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_2GEBGLjqEfGlPdn3R72URQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_2GEBG7jqEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_bftrALjeEfGlPdn3R72URQ" name="emergenciaId" dataType="_PcgnpKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bftrAbjeEfGlPdn3R72URQ" name="emergenciaIdInput" content="emergenciaIdInput" type="TYPE_CONTRACT_INPUT">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_PpyJYLjfEfGlPdn3R72URQ" name="emergenciaIdInput">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_PpyJYbjfEfGlPdn3R72URQ"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_Mz-noLjkEfGlPdn3R72URQ" name="decisionCobertura" dataType="_PcgnpKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Mz-nobjkEfGlPdn3R72URQ" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_IhfM0LjmEfGlPdn3R72URQ" name="coberturaCompleta" dataType="_PcgAkKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IhfM0bjmEfGlPdn3R72URQ" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_oc0PELjoEfGlPdn3R72URQ" name="adjudicacionId" dataType="_PcgnpKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_oc0PEbjoEfGlPdn3R72URQ" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_7imIILuQEfGrDIdYaw4B4g" name="fechaCierre" dataType="_PcgnoKvUEfGGjYEUN-iB-A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_7imIIbuQEfGrDIdYaw4B4g" content="" returnType="java.util.Date"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Pe-FwKvUEfGGjYEUN-iB-A">
        <targetForm xmi:type="expression:Expression" xmi:id="_0bgHpbumEfG4kNqMMwVcrQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Pe-FwqvUEfGGjYEUN-iB-A">
        <targetForm xmi:type="expression:Expression" xmi:id="_Pe-Fw6vUEfGGjYEUN-iB-A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PkhUIKvUEfGGjYEUN-iB-A" target="_Pg8bsKvUEfGGjYEUN-iB-A" source="_Pg2VEKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PkhUIavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PkhUIqvUEfGGjYEUN-iB-A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pk0PEKvUEfGGjYEUN-iB-A" name="Enviar ofertas igualmente" target="_PgS7cKvUEfGGjYEUN-iB-A" source="_Pg8bsKvUEfGGjYEUN-iB-A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pk0PEavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pk0PEqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PnzRoKvUEfGGjYEUN-iB-A" name="Sí" target="_PgS7cKvUEfGGjYEUN-iB-A" source="_PiBZwKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PnzRoavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_PnzRoqvUEfGGjYEUN-iB-A" name="newScript()" content="coberturaCompleta == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_RbodULjmEfGlPdn3R72URQ" name="coberturaCompleta" dataType="_PcgAkKvUEfGGjYEUN-iB-A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pn7NcKvUEfGGjYEUN-iB-A" name="No" target="_Pg2VEKvUEfGGjYEUN-iB-A" source="_PiBZwKvUEfGGjYEUN-iB-A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pn7NcavUEfGGjYEUN-iB-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pn7NcqvUEfGGjYEUN-iB-A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6MQ7sKxYEfG6DcibwtxsHw" target="_PiBZwKvUEfGGjYEUN-iB-A" source="_EtxyoKxZEfG6DcibwtxsHw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6MQ7saxYEfG6DcibwtxsHw"/>
        <condition xmi:type="expression:Expression" xmi:id="_6MQ7sqxYEfG6DcibwtxsHw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aaaaYLjfEfGlPdn3R72URQ" target="_SjwnMLjfEfGlPdn3R72URQ" source="_Pfx-EKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aabBcLjfEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_aabBcbjfEfGlPdn3R72URQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_e_JUYLjgEfGlPdn3R72URQ" target="_eksNALjgEfGlPdn3R72URQ" source="_SjwnMLjfEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_e_JUYbjgEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_e_JUYrjgEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7VKHsLjgEfGlPdn3R72URQ" target="_PhdZEKvUEfGGjYEUN-iB-A" source="_9a2B0LjgEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7VKHsbjgEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7VKHsrjgEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-XpoULjgEfGlPdn3R72URQ" target="_9a2B0LjgEfGlPdn3R72URQ" source="_eksNALjgEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-XpoUbjgEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_-XpoUrjgEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7wREcLjiEfGlPdn3R72URQ" target="_EtxyoKxZEfG6DcibwtxsHw" source="_PhdZEKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7wRrgLjiEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7wRrgbjiEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ARtkcLjlEfGlPdn3R72URQ" name="Reformular lotes o reabrir convocatoria" target="_SjwnMLjfEfGlPdn3R72URQ" source="_Pg8bsKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ARtkcbjlEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ARtkcrjlEfGlPdn3R72URQ" name="newScript()" content="decisionCobertura == &quot;REABRIR&quot; || decisionCobertura == &quot;REFORMULAR&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_kqJ9ILjlEfGlPdn3R72URQ" name="decisionCobertura" dataType="_PcgnpKvUEfGGjYEUN-iB-A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gd8UALjoEfGlPdn3R72URQ" target="_PhoYMKvUEfGGjYEUN-iB-A" source="_PgS7cKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gd87ELjoEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_gd87EbjoEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LLktILjpEfGlPdn3R72URQ" target="_Ph1zkKvUEfGGjYEUN-iB-A" source="_PhoYMKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LLktIbjpEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_LLktIrjpEfGlPdn3R72URQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_77ML8LjrEfGlPdn3R72URQ" target="_66GiYLjrEfGlPdn3R72URQ" source="_Ph1zkKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_77ML8bjrEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_77ML8rjrEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8TEgcLjrEfGlPdn3R72URQ" target="_YhNmoLjrEfGlPdn3R72URQ" source="_66GiYLjrEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8TFHgLjrEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8TFHgbjrEfGlPdn3R72URQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8zRDcLjrEfGlPdn3R72URQ" target="_2GDaALjqEfGlPdn3R72URQ" source="_66GiYLjrEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8zRDcbjrEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8zRDcrjrEfGlPdn3R72URQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JvfpULjsEfGlPdn3R72URQ" target="_JMvhkLjsEfGlPdn3R72URQ" source="_YhNmoLjrEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JvfpUbjsEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JvfpUrjsEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KGhCMLjsEfGlPdn3R72URQ" target="_JMvhkLjsEfGlPdn3R72URQ" source="_2GDaALjqEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KGhCMbjsEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KGhCMrjsEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WS9J4LjsEfGlPdn3R72URQ" target="_PhxiIKvUEfGGjYEUN-iB-A" source="_JMvhkLjsEfGlPdn3R72URQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WS9w8LjsEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_WS9w8bjsEfGlPdn3R72URQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fQyAgLjsEfGlPdn3R72URQ" target="_PjA4QKvUEfGGjYEUN-iB-A" source="_PhxiIKvUEfGGjYEUN-iB-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fQyAgbjsEfGlPdn3R72URQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_fQyAgrjsEfGlPdn3R72URQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_6KsysKvaEfGGjYEUN-iB-A" name="Empleado municipal" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_FfUhkKvbEfGGjYEUN-iB-A" name="Empleado centro coordinador"/>
      <actors xmi:type="process:Actor" xmi:id="_SeZAEKvbEfGGjYEUN-iB-A" name="Responsable ONG"/>
      <contract xmi:type="process:Contract" xmi:id="_Pe-s0KvUEfGGjYEUN-iB-A">
        <inputs xmi:type="process:ContractInput" xmi:id="_hQiaILjeEfGlPdn3R72URQ" name="emergenciaIdInput">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_hQiaIbjeEfGlPdn3R72URQ"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7pgKvUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7pgavUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7pgqvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7pg6vUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7phKvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7phavUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7phqvUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7ph6vUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7piKvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7piavUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7piqvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7pi6vUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Pe7pjKvUEfGGjYEUN-iB-A">
        <name xmi:type="expression:Expression" xmi:id="_Pe7pjavUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Pe7pjqvUEfGGjYEUN-iB-A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_PcgAkKvUEfGGjYEUN-iB-A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_PcgnoKvUEfGGjYEUN-iB-A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_PcgnoavUEfGGjYEUN-iB-A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_PcgnoqvUEfGGjYEUN-iB-A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Pcgno6vUEfGGjYEUN-iB-A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_PcgnpKvUEfGGjYEUN-iB-A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_PcgnpavUEfGGjYEUN-iB-A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_PchOsKvUEfGGjYEUN-iB-A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_PchOsavUEfGGjYEUN-iB-A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_PceLYKvUEfGGjYEUN-iB-A" type="Process" element="_PccWMKvUEfGGjYEUN-iB-A" name="RescueSync - habilitación- 1.0 - 1.0 (1)" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_PfDlUKvUEfGGjYEUN-iB-A" type="2007" element="_PdZ_gKvUEfGGjYEUN-iB-A">
      <children xmi:type="notation:DecorationNode" xmi:id="_PfEMZKvUEfGGjYEUN-iB-A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_PfEMZavUEfGGjYEUN-iB-A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_PfmX4KvUEfGGjYEUN-iB-A" type="3007" element="_PflJwKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PfmX5avUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PfmX5qvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PfzzQKvUEfGGjYEUN-iB-A" type="3002" element="_Pfx-EKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pf0aUKvUEfGGjYEUN-iB-A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Pf0aUavUEfGGjYEUN-iB-A" x="-1" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PfzzQavUEfGGjYEUN-iB-A" x="180" y="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PgUJkKvUEfGGjYEUN-iB-A" type="3005" element="_PgS7cKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PgUJkqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgUJkavUEfGGjYEUN-iB-A" x="1600" y="57" width="158" height="79"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PfmX4avUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PfmX4qvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PfmX46vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PfmX56vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PfmX5KvUEfGGjYEUN-iB-A" x="53" y="10" width="3952" height="203"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PgZpIKvUEfGGjYEUN-iB-A" type="3007" element="_PgZCEKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PgZpJavUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PgZpJqvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Pg28IKvUEfGGjYEUN-iB-A" type="3005" element="_Pg2VEKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pg28IqvUEfGGjYEUN-iB-A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pg28IavUEfGGjYEUN-iB-A" x="1378" y="242" width="145" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pg9p0KvUEfGGjYEUN-iB-A" type="3008" element="_Pg8bsKvUEfGGjYEUN-iB-A" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pg9p0qvUEfGGjYEUN-iB-A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Pg9p06vUEfGGjYEUN-iB-A" x="-1" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pg9p0avUEfGGjYEUN-iB-A" x="1429" y="142"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sj5KELjfEfGlPdn3R72URQ" type="3005" element="_SjwnMLjfEfGlPdn3R72URQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sj5xILjfEfGlPdn3R72URQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sj5KEbjfEfGlPdn3R72URQ" x="125" y="128" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YhONvLjrEfGlPdn3R72URQ" type="3005" element="_YhNmoLjrEfGlPdn3R72URQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_YhONvrjrEfGlPdn3R72URQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YhONvbjrEfGlPdn3R72URQ" x="2439" y="170" width="141" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PgZpIavUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PgZpIqvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PgZpI6vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PgZpJ6vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PgZpJKvUEfGGjYEUN-iB-A" x="48" y="203" width="3957" height="374"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PhMTUavUEfGGjYEUN-iB-A" type="3007" element="_PhMTUKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PhM6YKvUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PhM6YavUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PhdZGavUEfGGjYEUN-iB-A" type="3027" element="_PhdZEKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PheAIKvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhdZGqvUEfGGjYEUN-iB-A" x="737" y="145" width="147" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pho_SKvUEfGGjYEUN-iB-A" type="3027" element="_PhoYMKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhpmUavUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhpmUKvUEfGGjYEUN-iB-A" x="1809" y="139" width="124" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PhyJOKvUEfGGjYEUN-iB-A" type="3027" element="_PhxiIKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PhyJOqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhyJOavUEfGGjYEUN-iB-A" x="2930" y="134" width="142" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ph2aoKvUEfGGjYEUN-iB-A" type="3027" element="_Ph1zkKvUEfGGjYEUN-iB-A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ph2aoqvUEfGGjYEUN-iB-A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ph2aoavUEfGGjYEUN-iB-A" x="2056" y="135" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PiCA0KvUEfGGjYEUN-iB-A" type="3008" element="_PiBZwKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiCA0qvUEfGGjYEUN-iB-A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PiCA06vUEfGGjYEUN-iB-A" x="1"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiCA0avUEfGGjYEUN-iB-A" x="1429" y="160"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EtxyqaxZEfG6DcibwtxsHw" type="3027" element="_EtxyoKxZEfG6DcibwtxsHw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Etxyq6xZEfG6DcibwtxsHw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EtxyqqxZEfG6DcibwtxsHw" x="1087" y="144" width="154" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ektbILjgEfGlPdn3R72URQ" type="3017" element="_eksNALjgEfGlPdn3R72URQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ektbIrjgEfGlPdn3R72URQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ektbI7jgEfGlPdn3R72URQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ektbIbjgEfGlPdn3R72URQ" x="180" y="155"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9a2o6LjgEfGlPdn3R72URQ" type="3027" element="_9a2B0LjgEfGlPdn3R72URQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9a2o6rjgEfGlPdn3R72URQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9a2o6bjgEfGlPdn3R72URQ" x="403" y="143" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_66HJcLjrEfGlPdn3R72URQ" type="3009" element="_66GiYLjrEfGlPdn3R72URQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_66HJcrjrEfGlPdn3R72URQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_66HJc7jrEfGlPdn3R72URQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_66HJcbjrEfGlPdn3R72URQ" x="2322" y="148"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JMwIoLjsEfGlPdn3R72URQ" type="3009" element="_JMvhkLjsEfGlPdn3R72URQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_JMwIorjsEfGlPdn3R72URQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_JMwIo7jsEfGlPdn3R72URQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JMwIobjsEfGlPdn3R72URQ" x="2698" y="148"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PjCGYKvUEfGGjYEUN-iB-A" type="3003" element="_PjA4QKvUEfGGjYEUN-iB-A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PjCGYqvUEfGGjYEUN-iB-A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PjCGY6vUEfGGjYEUN-iB-A" y="9"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PjCGYavUEfGGjYEUN-iB-A" x="3234" y="155"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PhMTUqvUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PhMTU6vUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PhMTVKvUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PhM6YqvUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PhMTVavUEfGGjYEUN-iB-A" x="48" y="577" width="3957" height="283"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_PiG5UKvUEfGGjYEUN-iB-A" type="3007" element="_PiGSQKvUEfGGjYEUN-iB-A">
          <children xmi:type="notation:DecorationNode" xmi:id="_PiG5VavUEfGGjYEUN-iB-A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PiG5VqvUEfGGjYEUN-iB-A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_2GEoILjqEfGlPdn3R72URQ" type="3005" element="_2GDaALjqEfGlPdn3R72URQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2GEoIrjqEfGlPdn3R72URQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2GEoIbjqEfGlPdn3R72URQ" x="2450" y="83" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PiG5UavUEfGGjYEUN-iB-A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PiG5UqvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PiG5U6vUEfGGjYEUN-iB-A" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PiG5V6vUEfGGjYEUN-iB-A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiG5VKvUEfGGjYEUN-iB-A" x="48" y="860" width="3957" height="285"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_PfEMYKvUEfGGjYEUN-iB-A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_PfEMYavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_PfEMYqvUEfGGjYEUN-iB-A" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_PfEMZqvUEfGGjYEUN-iB-A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PfEMY6vUEfGGjYEUN-iB-A" width="3380" height="1447"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_PceLYavUEfGGjYEUN-iB-A"/>
    <edges xmi:type="notation:Connector" xmi:id="_Pkh7MKvUEfGGjYEUN-iB-A" type="4001" element="_PkhUIKvUEfGGjYEUN-iB-A" source="_Pg28IKvUEfGGjYEUN-iB-A" target="_Pg9p0KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pkh7M6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pkh7NKvUEfGGjYEUN-iB-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pkh7MavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pkh7MqvUEfGGjYEUN-iB-A" points="[0, 0, 0, 63]$[0, -63, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pk02IKvUEfGGjYEUN-iB-A" type="4001" element="_Pk0PEKvUEfGGjYEUN-iB-A" source="_Pg9p0KvUEfGGjYEUN-iB-A" target="_PgUJkKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pk02I6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pk02JKvUEfGGjYEUN-iB-A" x="-64" y="-1"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pk02IavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pk02IqvUEfGGjYEUN-iB-A" points="[-19, -34, -152, 249]$[-19, -283, -152, 0]$[131, -283, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qQXDgK1nEfGhg4iXH2Bxcg" id="(0.9302325581395349,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_R5CWoKvjEfGPjbJOghg_xg" id="(0.012658227848101266,0.4936708860759494)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PnzRo6vUEfGGjYEUN-iB-A" type="4001" element="_PnzRoKvUEfGGjYEUN-iB-A" source="_PiCA0KvUEfGGjYEUN-iB-A" target="_PgUJkKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pnz4sKvUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pnz4savUEfGGjYEUN-iB-A" x="16" y="14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PnzRpKvUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PnzRpavUEfGGjYEUN-iB-A" points="[4, -17, -283, 610]$[209, -17, -78, 610]$[209, -233, -78, 394]$[212, -233, -75, 394]$[212, -617, -75, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MjYSYKxYEfG6DcibwtxsHw" id="(0.8604651162790697,0.8604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3QDpQKxYEfG6DcibwtxsHw" id="(0.8417721518987342,0.9367088607594937)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pn70gKvUEfGGjYEUN-iB-A" type="4001" element="_Pn7NcKvUEfGGjYEUN-iB-A" source="_PiCA0KvUEfGGjYEUN-iB-A" target="_Pg28IKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pn70g6vUEfGGjYEUN-iB-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pn70hKvUEfGGjYEUN-iB-A" x="6" y="-2"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pn70gavUEfGGjYEUN-iB-A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pn70gqvUEfGGjYEUN-iB-A" points="[-2, 0, -8, 225]$[-2, -220, -8, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6yngsLjzEfG4o_5nuudFfg" id="(0.5348837209302325,0.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gTcdwLj0EfG4o_5nuudFfg" id="(0.5517241379310345,0.9305555555555556)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6MRiwKxYEfG6DcibwtxsHw" type="4001" element="_6MQ7sKxYEfG6DcibwtxsHw" source="_EtxyqaxZEfG6DcibwtxsHw" target="_PiCA0KvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6MSJ0axYEfG6DcibwtxsHw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6MSJ0qxYEfG6DcibwtxsHw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6MRiwaxYEfG6DcibwtxsHw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6MSJ0KxYEfG6DcibwtxsHw" points="[-69, -26, 19, 57]$[-69, -87, 19, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6MSw4KxYEfG6DcibwtxsHw" id="(1.0,0.35064935064935066)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6MSw4axYEfG6DcibwtxsHw" id="(0.046511627906976744,0.4186046511627907)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aabogLjfEfGlPdn3R72URQ" type="4001" element="_aaaaYLjfEfGlPdn3R72URQ" source="_PfzzQKvUEfGGjYEUN-iB-A" target="_Sj5KELjfEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aacPkLjfEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aacPkbjfEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aabogbjfEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aabogrjfEfGlPdn3R72URQ" points="[-5, -4, -306, -268]$[231, 266, -70, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aaddsLjfEfGlPdn3R72URQ" id="(1.0,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_e_J7cLjgEfGlPdn3R72URQ" type="4001" element="_e_JUYLjgEfGlPdn3R72URQ" source="_Sj5KELjfEfGlPdn3R72URQ" target="_ektbILjgEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_e_J7c7jgEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_e_J7dLjgEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_e_J7cbjgEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_e_J7crjgEfGlPdn3R72URQ" points="[-67, 39, 3, -270]$[-67, 294, 3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e_LJkLjgEfGlPdn3R72URQ" id="(1.0,0.44285714285714284)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7VKuwLjgEfGlPdn3R72URQ" type="4001" element="_7VKHsLjgEfGlPdn3R72URQ" source="_9a2o6LjgEfGlPdn3R72URQ" target="_PhdZGavUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7VKuw7jgEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7VKuxLjgEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7VKuwbjgEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7VKuwrjgEfGlPdn3R72URQ" points="[0, 0, -436, 112]$[363, -115, -73, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7VL84LjgEfGlPdn3R72URQ" id="(1.0,0.4025974025974026)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-XpoU7jgEfGlPdn3R72URQ" type="4001" element="_-XpoULjgEfGlPdn3R72URQ" source="_ektbILjgEfGlPdn3R72URQ" target="_9a2o6LjgEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-XqPYLjgEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-XqPYbjgEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-XpoVLjgEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-XpoVbjgEfGlPdn3R72URQ" points="[-9, -2, -324, -40]$[238, 45, -77, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-Xq2cLjgEfGlPdn3R72URQ" id="(1.0,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7wRrgrjiEfGlPdn3R72URQ" type="4001" element="_7wREcLjiEfGlPdn3R72URQ" source="_PhdZGavUEfGGjYEUN-iB-A" target="_EtxyqaxZEfG6DcibwtxsHw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7wSSkLjiEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7wSSkbjiEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7wRrg7jiEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7wRrhLjiEfGlPdn3R72URQ" points="[0, 0, -181, -122]$[171, 135, -10, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7wS5oLjiEfGlPdn3R72URQ" id="(1.0,0.4246575342465753)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7wS5objiEfGlPdn3R72URQ" id="(0.012987012987012988,0.5131578947368421)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ARzrELjlEfGlPdn3R72URQ" type="4001" element="_ARtkcLjlEfGlPdn3R72URQ" source="_Pg9p0KvUEfGGjYEUN-iB-A" target="_Sj5KELjfEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ARzrE7jlEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ARzrFLjlEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ARzrEbjlEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ARzrErjlEfGlPdn3R72URQ" points="[-43, -10, 394, -104]$[-418, -10, 19, -104]$[-418, 59, 19, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AR0SILjlEfGlPdn3R72URQ" id="(0.06976744186046512,0.5581395348837209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_maFr4Lj0EfG4o_5nuudFfg" id="(0.9642857142857143,0.5428571428571428)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gd87ErjoEfGlPdn3R72URQ" type="4001" element="_gd8UALjoEfGlPdn3R72URQ" source="_PgUJkKvUEfGGjYEUN-iB-A" target="_Pho_SKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gd87FbjoEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gd87FrjoEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gd87E7joEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gd87FLjoEfGlPdn3R72URQ" points="[0, 0, -177, -504]$[181, 528, 4, 24]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gd-JMLjoEfGlPdn3R72URQ" id="(1.0,0.3670886075949367)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LLl7QLjpEfGlPdn3R72URQ" type="4001" element="_LLktILjpEfGlPdn3R72URQ" source="_Pho_SKvUEfGGjYEUN-iB-A" target="_Ph2aoKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LLl7Q7jpEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LLl7RLjpEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LLl7QbjpEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LLl7QrjpEfGlPdn3R72URQ" points="[0, 0, -102, 81]$[49, -88, -53, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LLnJYLjpEfGlPdn3R72URQ" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_77ML87jrEfGlPdn3R72URQ" type="4001" element="_77ML8LjrEfGlPdn3R72URQ" source="_Ph2aoKvUEfGGjYEUN-iB-A" target="_66HJcLjrEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_77MzALjrEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_77MzAbjrEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_77ML9LjrEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_77ML9bjrEfGlPdn3R72URQ" points="[0, 0, -99, -18]$[97, 5, -2, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_77NaELjrEfGlPdn3R72URQ" id="(1.0,0.44285714285714284)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8TFukLjrEfGlPdn3R72URQ" type="4001" element="_8TEgcLjrEfGlPdn3R72URQ" source="_66HJcLjrEfGlPdn3R72URQ" target="_YhONvLjrEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8TFuk7jrEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8TFulLjrEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8TFukbjrEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8TFukrjrEfGlPdn3R72URQ" points="[-7, 0, -119, 331]$[-7, -325, -119, 6]$[90, -325, -22, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8TG8sLjrEfGlPdn3R72URQ" id="(0.627906976744186,0.023255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8TG8sbjrEfGlPdn3R72URQ" id="(0.15602836879432624,0.3142857142857143)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8zRqgLjrEfGlPdn3R72URQ" type="4001" element="_8zRDcLjrEfGlPdn3R72URQ" source="_66HJcLjrEfGlPdn3R72URQ" target="_2GEoILjqEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8zRqg7jrEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8zRqhLjrEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8zRqgbjrEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8zRqgrjrEfGlPdn3R72URQ" points="[3, 5, -110, -205]$[3, 214, -110, 4]$[53, 214, -60, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8zSRkLjrEfGlPdn3R72URQ" id="(0.4186046511627907,0.8837209302325582)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JvfpU7jsEfGlPdn3R72URQ" type="4001" element="_JvfpULjsEfGlPdn3R72URQ" source="_YhONvLjrEfGlPdn3R72URQ" target="_JMwIoLjsEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JvgQYLjsEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JvgQYbjsEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JvfpVLjsEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JvfpVbjsEfGlPdn3R72URQ" points="[-3, 30, 26, -259]$[-26, 303, 3, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jvg3cLjsEfGlPdn3R72URQ" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__YWgQLj0EfG4o_5nuudFfg" id="(0.5581395348837209,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KGhCM7jsEfGlPdn3R72URQ" type="4001" element="_KGhCMLjsEfGlPdn3R72URQ" source="_2GEoILjqEfGlPdn3R72URQ" target="_JMwIoLjsEfGlPdn3R72URQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KGhpQLjsEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KGhpQbjsEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KGhCNLjsEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KGhCNbjsEfGlPdn3R72URQ" points="[0, 0, -157, 236]$[154, -248, -3, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KGiQULjsEfGlPdn3R72URQ" id="(1.0,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__BJhMLj0EfG4o_5nuudFfg" id="(0.4186046511627907,0.9534883720930233)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WS9w8rjsEfGlPdn3R72URQ" type="4001" element="_WS9J4LjsEfGlPdn3R72URQ" source="_JMwIoLjsEfGlPdn3R72URQ" target="_PhyJOKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WS9w9bjsEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WS9w9rjsEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WS9w87jsEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WS9w9LjsEfGlPdn3R72URQ" points="[-6, -13, -228, 95]$[168, -111, -54, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WS-YALjsEfGlPdn3R72URQ" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fQynkLjsEfGlPdn3R72URQ" type="4001" element="_fQyAgLjsEfGlPdn3R72URQ" source="_PhyJOKvUEfGGjYEUN-iB-A" target="_PjCGYKvUEfGGjYEUN-iB-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fQynk7jsEfGlPdn3R72URQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fQynlLjsEfGlPdn3R72URQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fQynkbjsEfGlPdn3R72URQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fQynkrjsEfGlPdn3R72URQ" points="[0, 0, -227, -13]$[225, 24, -2, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fQz1sLjsEfGlPdn3R72URQ" id="(1.0,0.43661971830985913)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
